export const animals = [
    {"kanji": "海豹","kana": "あざらし, かいひょう","eng": "true seal (animal), earless seal"},
    {"kanji": "浅蜊","kana": "あさり","eng": "Manila clam (Ruditapes philippinarum)"},
    {"kanji": "海驢","kana": "あしか, みち","eng": "eared seal (esp. the California sea lion, Zalophus californianus), sea lion"},
    {"kanji": "葦鹿","kana": "あしか","eng": "eared seal (esp. the California sea lion, Zalophus californianus), sea lion"},
    {"kanji": "雨虎","kana": "あめふらし","eng": "sea hare (esp. species Aplysia kurodai)"},
    {"kanji": "雨降","kana": "あめふり, あめふらし","eng": "rainfall, rainy weather, sea hare (esp. species Aplysia kurodai)"},
    {"kanji": "洗熊","kana": "あらいぐま","eng": "common raccoon (Procyon lotor)"},
    {"kanji": "浣熊","kana": "あらいぐま","eng": "common raccoon (Procyon lotor)"},
    {"kanji": "蟻食","kana": "ありくい","eng": "anteater"},
    {"kanji": "食蟻獣","kana": "ありくい","eng": "anteater"},
    {"kanji": "鮑","kana": "あわび","eng": "abalone, ear shell"},
    {"kanji": "鰒","kana": "ふぐ, あわび","eng": "puffer fish, blow fish, fugu, globefish, swellfish, abalone, ear shell"},
    {"kanji": "石決明","kana": "あわび, せっけつめい","eng": "abalone, ear shell, powdered abalone shell (used in Chinese medicine)"},
    {"kanji": "烏賊","kana": "いか","eng": "cuttlefish, squid"},
    {"kanji": "磯巾着","kana": "いそぎんちゃく","eng": "sea anemone"},
    {"kanji": "菟葵","kana": "いそぎんちゃく","eng": "sea anemone"},
    {"kanji": "鼬","kana": "いたち","eng": "weasel (esp. the Japanese weasel, Mustela itatsi)"},
    {"kanji": "鼬鼠","kana": "いたち","eng": "weasel (esp. the Japanese weasel, Mustela itatsi)"},
    {"kanji": "一角","kana": "いっかく","eng": "narwhal"},
    {"kanji": "稲子","kana": "いなご","eng": "rice grasshopper (of genus Oxya)"},
    {"kanji": "蝗","kana": "いなご, こう, いなむし, おおねむし, ばった","eng": "rice grasshopper (of genus Oxya), rice pest, grasshopper, locust (of superfamily Acridoidea)"},
    {"kanji": "猪","kana": "いのしし, しし, い","eng": "wild boar, beast (esp. one used for its meat, such as a boar or a deer), hog (esp. a wild boar, but also including the domesticated pig)"},
    {"kanji": "井守","kana": "いもり","eng": "newt (esp. the Japanese fire belly newt, Cynops pyrrhogaster)"},
    {"kanji": "海豚","kana": "いるか","eng": "dolphin (or other small toothed whales, such as porpoises, belugas, etc.)"},
    {"kanji": "兎","kana": "うさぎ, う","eng": "rabbit, hare, coney, cony, lagomorph (esp. leporids)"},
    {"kanji": "海胆","kana": "うに","eng": "sea urchin"},
    {"kanji": "海栗","kana": "うに","eng": "sea urchin"},
    {"kanji": "海牛","kana": "うみうし, かいぎゅう","eng": "sea slug (various orthogastropod species, esp. of order Nudibranchia), nudibranch, sirenian (any aquatic mammal of order Sirenia, incl. manatees, and dugongs), sea cow"},
    {"kanji": "海蛍","kana": "うみほたる","eng": "sea firefly (Vargula hilgendorfii), seed shrimp"},
    {"kanji": "襟巻蜥蜴","kana": "えりまきとかげ","eng": "frilled lizard (Chlamydosaurus kingii), frill-necked lizard"},
    {"kanji": "鸚鵡貝","kana": "おうむがい","eng": "chambered nautilus (esp. species Nautilus pompilius)"},
    {"kanji": "狼","kana": "おおかみ, おおかめ, おいぬ","eng": "wolf (Canis lupus)"},
    {"kanji": "御玉杓子","kana": "おたまじゃくし","eng": "ladle"},
    {"kanji": "膃肭臍","kana": "おっとせい","eng": "fur seal (esp. the northern fur seal, Callorhinus ursinus), Alaskan fur seal"},
    {"kanji": "蛙","kana": "かえる, かわず, かいる","eng": "frog"},
    {"kanji": "牡蠣","kana": "かき, ぼれい","eng": "oyster, oyster shell"},
    {"kanji": "蝸牛","kana": "かたつむり, かぎゅう, でんでんむし","eng": "snail, Cochlea"},
    {"kanji": "蟹","kana": "かに","eng": "crab"},
    {"kanji": "河馬","kana": "かば, かわうま","eng": "hippopotamus (Hippopotamus amphibius)"},
    {"kanji": "兜蝦","kana": "かぶとえび","eng": "tadpole shrimp (Triopsidae spp.), shield shrimp"},
    {"kanji": "兜蟹","kana": "かぶとがに","eng": "horseshoe crab"},
    {"kanji": "蝦蟇","kana": "がまがえる, がま, かま","eng": "toad (esp. the Japanese toad, Bufo japonicus)"},
    {"kanji": "蟇","kana": "ひきがえる, ひき, がまがえる, がま, かま","eng": "toad (esp. the Japanese toad, Bufo japonicus)"},
    {"kanji": "羚羊","kana": "れいよう, かもしか","eng": "antelope, serow, wild goat"},
    {"kanji": "川獺","kana": "かわうそ","eng": "otter (Lutra lutra)"},
    {"kanji": "狐","kana": "きつね, けつね, きつ","eng": "fox (esp. the red fox, Vulpes vulpes)"},
    {"kanji": "麒麟","kana": "きりん","eng": "giraffe (Giraffa camelopardalis)"},
    {"kanji": "鯨","kana": "くじら","eng": "whale (Cetacea spp.)"},
    {"kanji": "水母","kana": "くらげ, すいぼ","eng": "jellyfish"},
    {"kanji": "海月","kana": "くらげ","eng": "jellyfish"},
    {"kanji": "蝙蝠","kana": "こうもり, かわほり, へんぷく","eng": "bat (Chiroptera spp.)"},
    {"kanji": "犀","kana": "さい","eng": "rhinoceros"},
    {"kanji": "栄螺","kana": "さざえ, さざい","eng": "turban shell (any mollusc of the family Turbinidae, esp. the horned turban, Turbo cornutus)"},
    {"kanji": "拳螺","kana": "さざえ","eng": "turban shell (any mollusc of the family Turbinidae, esp. the horned turban, Turbo cornutus)"},
    {"kanji": "真田虫","kana": "さなだむし","eng": "tapeworm"},
    {"kanji": "条虫","kana": "じょうちゅう","eng": "cestode, tapeworm"},
    {"kanji": "珊瑚","kana": "さんご","eng": "coral"},
    {"kanji": "山椒魚","kana": "さんしょううお","eng": "salamander"},
    {"kanji": "獅子","kana": "しし","eng": "lion"},
    {"kanji": "蜆","kana": "しじみ","eng": "basket clam (Corbiculidae spp.), freshwater clam, freshwater mussel"},
    {"kanji": "縞馬","kana": "しまうま","eng": "zebra"},
    {"kanji": "斑馬","kana": "しまうま, まだらうま, はんば, ぶちうま","eng": "zebra, speckled horse"},
    {"kanji": "蝦蛄","kana": "しゃこ","eng": "mantis shrimp (any marine crustacean of order Stomatopoda, esp. the species Oratosquilla oratoria)"},
    {"kanji": "青竜蝦","kana": "しゃこ","eng": "mantis shrimp (any marine crustacean of order Stomatopoda, esp. the species Oratosquilla oratoria)"},
    {"kanji": "鯱","kana": "しゃち, しゃちほこ, しゃっちょこ, さちほこ","eng": "orca (Orcinus orca), killer whale, grampus, mythical carp with the head of a lion and the body of a fish (auspicious protectors of well-being)"},
    {"kanji": "儒艮","kana": "じゅごん","eng": "dugong (Dugong dugon), sea pig"},
    {"kanji": "水牛","kana": "すいぎゅう","eng": "water buffalo (Bubalus bubalis), domestic Asian water buffalo"},
    {"kanji": "鼈","kana": "すっぽん","eng": "Chinese soft-shelled turtle (Pelodiscus sinensis), soft-shelled turtle (Trionychidae)"},
    {"kanji": "海象","kana": "せいうち, かいぞう, かいしょう","eng": "walrus (Odobenus rosmarus), marine phenomenon"},
    {"kanji": "海馬","kana": "あしか, かいば, うみうま, とど, せいうち","eng": "eared seal (esp. the California sea lion, Zalophus californianus), sea lion, seahorse, sea horse, Steller's sea lion, Northern sea lion, walrus (Odobenus rosmarus)"},
    {"kanji": "蛸","kana": "たこ","eng": "octopus"},
    {"kanji": "章魚","kana": "たこ","eng": "octopus"},
    {"kanji": "鮹","kana": "たこ","eng": "octopus"},
    {"kanji": "壁蝨","kana": "だに","eng": "tick (Acari spp.), mite"},
    {"kanji": "田螺","kana": "たにし","eng": "pond snail (Viviparidae spp.)"},
    {"kanji": "団子虫","kana": "だんごむし","eng": "pillbug, pill bug, woodlouse, sowbug, sow bug, slater"},
    {"kanji": "蜥蜴","kana": "とかげ, せきえき","eng": "lizard"},
    {"kanji": "石竜子","kana": "とかげ","eng": "lizard"},
    {"kanji": "馴鹿","kana": "となかい, じゅんろく","eng": "reindeer (Rangifer tarandus)"},
    {"kanji": "虎","kana": "とら","eng": "tiger (Panthera tigris)"},
    {"kanji": "樹懶","kana": "なまけもの","eng": "sloth (Sth. Am. tree-dwelling mammal)"},
    {"kanji": "海鼠","kana": "なまこ, かいそ, こ","eng": "sea cucumber (Holothuroidea spp.)"},
    {"kanji": "蛞蝓","kana": "なめくじ","eng": "slug"},
    {"kanji": "鼠","kana": "ねずみ, ねず","eng": "mouse, rat"},
    {"kanji": "獏","kana": "ばく","eng": "tapir (Tapirus spp.)"},
    {"kanji": "貘","kana": "ばく","eng": "tapir (Tapirus spp.)"},
    {"kanji": "波布","kana": "はぶ","eng": "habu (Trimeresurus flavoviridis), yellow-spotted pit viper"},
    {"kanji": "飯匙倩","kana": "はぶ","eng": "habu (Trimeresurus flavoviridis), yellow-spotted pit viper"},
    {"kanji": "蛤","kana": "かえる, はまぐり","eng": "frog, common orient clam (Meretrix lusoria)"},
    {"kanji": "文蛤","kana": "はまぐり","eng": "common orient clam (Meretrix lusoria)"},
    {"kanji": "蚌","kana": "はまぐり","eng": "common orient clam (Meretrix lusoria)"},
    {"kanji": "蜩","kana": "ひぐらし","eng": "evening cicada (Tanna japonensis)"},
    {"kanji": "茅蜩","kana": "ひぐらし","eng": "evening cicada (Tanna japonensis)"},
    {"kanji": "海星","kana": "ひとで","eng": "starfish, sea star, asteroid, any echinoderm of the class Asteroidea"},
    {"kanji": "人手","kana": "ひとで","eng": "starfish, sea star, asteroid, any echinoderm of the class Asteroidea, someone else's hands, other hands"},
    {"kanji": "海盤車","kana": "ひとで","eng": "starfish, sea star, asteroid, any echinoderm of the class Asteroidea"},
    {"kanji": "狒狒","kana": "ひひ","eng": "baboon"},
    {"kanji": "豹","kana": "ひょう","eng": "leopard (Panthera pardus), panther"},
    {"kanji": "蛭","kana": "ひる","eng": "leech"},
    {"kanji": "富士壺","kana": "ふじつぼ","eng": "acorn barnacle (Balanomorpha spp.)"},
    {"kanji": "船虫","kana": "ふなむし","eng": "wharf roach (species of isopod closely related to the sea slater; Ligia exotica)"},
    {"kanji": "帆立貝","kana": "ほたてがい","eng": "Japanese scallop (Patinopecten yessoensis), Yesso scallop"},
    {"kanji": "法螺貝","kana": "ほらがい","eng": "conch (esp. Charonia tritonis), trumpet shell"},
    {"kanji": "吹螺","kana": "ほらがい","eng": "conch (esp. Charonia tritonis), trumpet shell"},
    {"kanji": "梭尾螺","kana": "ほらがい","eng": "conch (esp. Charonia tritonis), trumpet shell"},
    {"kanji": "蝮","kana": "まむし, はみ, くちばみ, たじひ","eng": "pit viper (esp. the mamushi, Gloydius blomhoffi)"},
    {"kanji": "微塵子","kana": "みじんこ","eng": "water flea (Daphnia spp.)"},
    {"kanji": "蚯蚓","kana": "みみず, めめず, きゅういん","eng": "earthworm"},
    {"kanji": "百足","kana": "むかで, ひゃくそく","eng": "centipede"},
    {"kanji": "蜈蚣","kana": "むかで","eng": "centipede"},
    {"kanji": "土竜","kana": "もぐら, むぐらもち, むぐら, もぐらもち, どりゅう","eng": "mole (Talpidae spp., esp. the small Japanese mole, Mogera imaizumii)"},
    {"kanji": "山羊","kana": "やぎ","eng": "goat"},
    {"kanji": "野羊","kana": "やぎ","eng": "goat"},
    {"kanji": "馬陸","kana": "やすで","eng": "millipede"},
    {"kanji": "寄居虫","kana": "やどかり, ごうな, かみな","eng": "hermit crab"},
    {"kanji": "山荒","kana": "やまあらし","eng": "porcupine (any mammal of suborder Hystricomorpha)"},
    {"kanji": "豪猪","kana": "やまあらし","eng": "porcupine (any mammal of suborder Hystricomorpha)"},
    {"kanji": "家守","kana": "やもり","eng": "gecko, house lizard"},
    {"kanji": "駱駝","kana": "らくだ","eng": "camel"},
    {"kanji": "海獺","kana": "らっこ, うみうそ, うみおそ","eng": "sea otter (Enhydra lutris), sea lion"},
    {"kanji": "猟虎","kana": "らっこ","eng": "sea otter (Enhydra lutris)"},
    {"kanji": "獺虎","kana": "らっこ","eng": "sea otter (Enhydra lutris)"},
    {"kanji": "騾馬","kana": "らば","eng": "mule"},
    {"kanji": "栗鼠","kana": "りす","eng": "squirrel (any mammal of family Sciuridae)"},
    {"kanji": "驢馬","kana": "ろば","eng": "donkey, ass"}
]