export const countries = [
    {"kanji": "氷州","kana": "アイスランド","eng": "Iceland"},
    {"kanji": "愛蘭","kana": "アイルランド","eng": "Ireland, Eire"},
    {"kanji": "阿富汗斯坦","kana": "アフガニスタン","eng": "Afghanistan"},
    {"kanji": "亜米利加","kana": "アメリカ","eng": "America"},
    {"kanji": "阿爾及","kana": "アルジェリア","eng": "Algeria"},
    {"kanji": "亜爾然丁","kana": "アルゼンチン","eng": "Argentina"},
    {"kanji": "英吉利","kana": "イギリス","eng": "Great Britain, United Kingdom"},
    {"kanji": "以色列","kana": "イスラエル","eng": "Israel"},
    {"kanji": "伊太利","kana": "イタリア, イタリヤ, イタリー","eng": "Italy"},
    {"kanji": "伊蘭","kana": "イラン","eng": "Iran"},
    {"kanji": "印度","kana": "インド","eng": "India"},
    {"kanji": "印度尼西亜","kana": "インドネシア","eng": "Indonesia"},
    {"kanji": "烏克蘭","kana": "ウクライナ","eng": "Ukraine"},
    {"kanji": "宇柳貝","kana": "ウルグアイ","eng": "Uruguay"},
    {"kanji": "厄瓜多","kana": "エクアドル","eng": "Ecuador"},
    {"kanji": "埃及","kana": "エジプト, エジブト","eng": "Egypt"},
    {"kanji": "濠太剌利","kana": "オーストラリア","eng": "Australia"},
    {"kanji": "墺太利","kana": "オーストリア","eng": "Austria"},
    {"kanji": "和蘭","kana": "オランダ","eng": "Holland, The Netherlands"},
    {"kanji": "阿蘭陀","kana": "オランダ","eng": "Holland, The Netherlands"},
    {"kanji": "加奈陀","kana": "カナダ","eng": "Canada"},
    {"kanji": "柬埔寨","kana": "カンボジア","eng": "Cambodia"},
    {"kanji": "幾内亜","kana": "ギニア","eng": "Guinea"},
    {"kanji": "玖馬","kana": "キューバ, クーバ","eng": "Cuba"},
    {"kanji": "希臘","kana": "ギリシャ, ギリシア","eng": "Greece"},
    {"kanji": "科威都","kana": "クウェート","eng": "Kuwait"},
    {"kanji": "象牙海岸","kana": "コートジボワール, ぞうげかいがん","eng": "(Republic of) Ivory Coast, Côte d'Ivoire"},
    {"kanji": "哥倫比亜","kana": "コロンビア","eng": "Colombia"},
    {"kanji": "牙買加","kana": "ジャマイカ","eng": "Jamaica"},
    {"kanji": "叙利亜","kana": "シリア","eng": "Syria"},
    {"kanji": "新嘉坡","kana": "シンガポール","eng": "Singapore"},
    {"kanji": "瑞西","kana": "スイス","eng": "Switzerland"},
    {"kanji": "瑞典","kana": "スウェーデン, スエーデン","eng": "Sweden"},
    {"kanji": "蘇丹","kana": "スーダン","eng": "Sudan"},
    {"kanji": "西班牙","kana": "スペイン","eng": "Spain"},
    {"kanji": "錫蘭","kana": "スリランカ, セイロン","eng": "Ceylon"},
    {"kanji": "塞爾維","kana": "セルビア","eng": "Serbia"},
    {"kanji": "泰","kana": "タイ","eng": "Thailand"},
    {"kanji": "泰国","kana": "タイ, タイコク","eng": "Thailand"},
    {"kanji": "突尼斯","kana": "チュニジア, テュニジア","eng": "Tunisia"},
    {"kanji": "智利","kana": "チリ","eng": "Chile"},
    {"kanji": "丁抹","kana": "デンマーク","eng": "Denmark"},
    {"kanji": "独逸","kana": "ドイツ","eng": "Germany"},
    {"kanji": "独乙","kana": "ドイツ","eng": "Germany"},
    {"kanji": "独国","kana": "ドイツ, どくこく","eng": "Germany"},
    {"kanji": "土耳古","kana": "トルコ","eng": "Turkey"},
    {"kanji": "尼加拉瓦","kana": "ニカラグア, ニカラグワ","eng": "Nicaragua"},
    {"kanji": "新西蘭","kana": "ニュージーランド, ニュージランド","eng": "New Zealand"},
    {"kanji": "諾威","kana": "ノルウェー","eng": "Norway"},
    {"kanji": "海地","kana": "ハイチ","eng": "Haiti"},
    {"kanji": "和地関","kana": "バチカン, ヴァチカン, バティカン, ヴァティカン","eng": "Vatican"},
    {"kanji": "巴奈馬","kana": "パナマ","eng": "Panama"},
    {"kanji": "巴拉圭","kana": "パラグアイ","eng": "Paraguay"},
    {"kanji": "洪牙利","kana": "ハンガリー","eng": "Hungary"},
    {"kanji": "比律賓","kana": "フィリピン, フイリピン","eng": "Philippines"},
    {"kanji": "芬蘭","kana": "フィンランド","eng": "Finland"},
    {"kanji": "不丹","kana": "ブータン","eng": "Bhutan"},
    {"kanji": "伯剌西爾","kana": "ブラジル","eng": "Brazil"},
    {"kanji": "仏蘭西","kana": "フランス","eng": "France"},
    {"kanji": "仏国","kana": "フランス, ふっこく","eng": "France"},
    {"kanji": "勃牙利","kana": "ブルガリア","eng": "Bulgaria"},
    {"kanji": "越南","kana": "ベトナム, えつなん","eng": "Vietnam"},
    {"kanji": "委内瑞拉","kana": "ベネズエラ","eng": "Venezuela"},
    {"kanji": "白露","kana": "ベラルーシ","eng": "Belarus"},
    {"kanji": "秘露","kana": "ペルー","eng": "Peru"},
    {"kanji": "白耳義","kana": "ベルギー","eng": "Belgium"},
    {"kanji": "波蘭","kana": "ポーランド","eng": "Poland"},
    {"kanji": "暮利比亜","kana": "ボリビア","eng": "Bolivia"},
    {"kanji": "葡萄牙","kana": "ポルトガル","eng": "Portugal"},
    {"kanji": "馬達加斯加","kana": "マダガスカル","eng": "Madagascar"},
    {"kanji": "馬来西亜","kana": "マレーシア","eng": "Malaysia"},
    {"kanji": "緬甸","kana": "ミャンマー, めんでん","eng": "Burma"},
    {"kanji": "墨西哥","kana": "メキシコ, メヒコ","eng": "Mexico"},
    {"kanji": "摩納哥","kana": "モナコ","eng": "Monaco"},
    {"kanji": "摩洛哥","kana": "モロッコ","eng": "Morocco"},
    {"kanji": "莫臥児","kana": "モンゴル, モール","eng": "Mongolia"},
    {"kanji": "蒙古","kana": "モンゴル, もうこ","eng": "Mongolia"},
    {"kanji": "黒山","kana": "モンテネグロ","eng": "Montenegro"},
    {"kanji": "利比亜","kana": "リビア","eng": "Libya"},
    {"kanji": "羅馬尼亜","kana": "ルーマニア","eng": "Romania, Rumania"},
    {"kanji": "黎巴嫩","kana": "レバノン","eng": "Lebanon"},
    {"kanji": "露西亜","kana": "ロシア, ロシヤ","eng": "Russia"}
];