export const n4 = [
    {"kanji": "野菜","kana": "やさい","eng": "vegetable"},
    {"kanji": "間","kana": "あいだ, ま","eng": "a space"},
    {"kanji": "上る","kana": "のぼる","eng": "to rise"},
    {"kanji": "郵便局","kana": "ゆうびんきょく","eng": "post office"},
    {"kanji": "味","kana": "あじ","eng": "flavour"},
    {"kanji": "明日","kana": "あす, あした","eng": "tomorrow"},
    {"kanji": "枝","kana": "えだ","eng": "branch; bow; bough; twig; limb, counter for long, thin things (i.e. swords)"},
    {"kanji": "集める","kana": "あつめる","eng": "to collect something"},
    {"kanji": "安心","kana": "あんしん","eng": "relief"},
    {"kanji": "以下","kana": "いか","eng": "less than"},
    {"kanji": "以外","kana": "いがい","eng": "with the exception of"},
    {"kanji": "医学","kana": "いがく","eng": "medical science"},
    {"kanji": "豚肉","kana": "ぶたにく","eng": "pork"},
    {"kanji": "意見","kana": "いけん","eng": "opinion"},
    {"kanji": "以上","kana": "いじょう","eng": "more than, this is all"},
    {"kanji": "急ぐ","kana": "いそぐ","eng": "to hurry"},
    {"kanji": "一度","kana": "いちど","eng": "once"},
    {"kanji": "動く","kana": "うごく","eng": "to move"},
    {"kanji": "写す","kana": "うつす","eng": "to copy or photograph"},
    {"kanji": "売り場","kana": "うりば","eng": "place where things are sold"},
    {"kanji": "運転","kana": "うんてん","eng": "to drive"},
    {"kanji": "運転手","kana": "うんてんしゅ","eng": "driver"},
    {"kanji": "運動","kana": "うんどう","eng": "to exercise"},
    {"kanji": "屋上","kana": "おくじょう","eng": "rooftop"},
    {"kanji": "送る","kana": "おくる","eng": "to send"},
    {"kanji": "起こす","kana": "おこす","eng": "to wake"},
    {"kanji": "行う","kana": "おこなう","eng": "to do"},
    {"kanji": "音","kana": "おと, おん, ね","eng": "sound, note"},
    {"kanji": "思い出す","kana": "おもいだす","eng": "to remember"},
    {"kanji": "思う","kana": "おもう","eng": "to think, to feel"},
    {"kanji": "親","kana": "おや","eng": "parents"},
    {"kanji": "下りる","kana": "おりる","eng": "to get off"},
    {"kanji": "終わり","kana": "おわり","eng": "the end"},
    {"kanji": "会場","kana": "かいじょう","eng": "assembly hall or meeting place"},
    {"kanji": "会話","kana": "かいわ","eng": "conversation"},
    {"kanji": "帰り","kana": "かえり","eng": "return"},
    {"kanji": "火事","kana": "かじ","eng": "fire"},
    {"kanji": "お金持ち","kana": "おかねもち","eng": "rich man"},
    {"kanji": "通う","kana": "かよう","eng": "to commute"},
    {"kanji": "代わり","kana": "かわり","eng": "substitute, alternate"},
    {"kanji": "考える","kana": "かんがえる","eng": "to consider"},
    {"kanji": "気","kana": "き, け","eng": "spirit, mood"},
    {"kanji": "聞こえる","kana": "きこえる","eng": "to be heard"},
    {"kanji": "気持ち","kana": "きもち","eng": "feeling, mood"},
    {"kanji": "着物","kana": "きもの","eng": "kimono"},
    {"kanji": "急","kana": "きゅう","eng": "urgent, steep"},
    {"kanji": "急行","kana": "きゅうこう","eng": "speedy, express"},
    {"kanji": "教会","kana": "きょうかい","eng": "church"},
    {"kanji": "空気","kana": "くうき","eng": "air, atmosphere"},
    {"kanji": "緑","kana": "みどり","eng": "green, greenery (esp. fresh verdure)"},
    {"kanji": "研究","kana": "けんきゅう","eng": "research"},
    {"kanji": "研究室","kana": "けんきゅうしつ","eng": "study room, laboratory"},
    {"kanji": "見物","kana": "けんぶつ","eng": "sightseeing"},
    {"kanji": "短い","kana": "みじかい","eng": "short"},
    {"kanji": "工業","kana": "こうぎょう","eng": "the manufacturing industry"},
    {"kanji": "高校","kana": "こうこう","eng": "high school"},
    {"kanji": "高校生","kana": "こうこうせい","eng": "high school student"},
    {"kanji": "戸","kana": "と","eng": "door (esp. Japanese-style), shutter; window shutter, entrance (to a home), narrows, counter for houses, households, apartments, etc."},
    {"kanji": "校長","kana": "こうちょう","eng": "headmaster"},
    {"kanji": "心","kana": "こころ","eng": "core, heart"},
    {"kanji": "小鳥","kana": "ことり","eng": "small bird"},
    {"kanji": "今度","kana": "こんど","eng": "now, next time"},
    {"kanji": "今夜","kana": "こんや","eng": "tonight"},
    {"kanji": "下がる","kana": "さがる","eng": "to get down, to descend"},
    {"kanji": "下げる","kana": "さげる","eng": "to hang, to lower, to move back"},
    {"kanji": "さ来月","kana": "さらいげつ","eng": "the month after next"},
    {"kanji": "さ来週","kana": "さらいしゅう","eng": "the week after next"},
    {"kanji": "字","kana": "じ, あざ","eng": "character"},
    {"kanji": "仕方","kana": "しかた","eng": "method"},
    {"kanji": "試験","kana": "しけん","eng": "examination"},
    {"kanji": "時代","kana": "じだい","eng": "era"},
    {"kanji": "下着","kana": "したぎ","eng": "underwear"},
    {"kanji": "品物","kana": "しなもの","eng": "goods"},
    {"kanji": "社会","kana": "しゃかい","eng": "society, public"},
    {"kanji": "社長","kana": "しゃちょう","eng": "company president"},
    {"kanji": "出発","kana": "しゅっぱつ","eng": "to depart"},
    {"kanji": "小学校","kana": "しょうがっこう","eng": "elementary school"},
    {"kanji": "食事","kana": "しょくじ","eng": "to have a meal"},
    {"kanji": "食料品","kana": "しょくりょうひん","eng": "groceries"},
    {"kanji": "知らせる","kana": "しらせる","eng": "to notify"},
    {"kanji": "人口","kana": "じんこう","eng": "population"},
    {"kanji": "親切","kana": "しんせつ","eng": "kindness"},
    {"kanji": "新聞社","kana": "しんぶんしゃ","eng": "newspaper company"},
    {"kanji": "水道","kana": "すいどう","eng": "water supply"},
    {"kanji": "西洋","kana": "せいよう","eng": "western countries"},
    {"kanji": "世界","kana": "せかい","eng": "the world"},
    {"kanji": "庭","kana": "にわ","eng": "garden; yard; courtyard, field (of action); area"},
    {"kanji": "大学生","kana": "だいがくせい","eng": "university student"},
    {"kanji": "大事","kana": "だいじ, おおごと","eng": "important, valuable, serious matter"},
    {"kanji": "台風","kana": "たいふう","eng": "typhoon"},
    {"kanji": "足す","kana": "たす","eng": "to add a number"},
    {"kanji": "正しい","kana": "ただしい","eng": "correct"},
    {"kanji": "立てる","kana": "たてる","eng": "to stand something up"},
    {"kanji": "建てる","kana": "たてる","eng": "to build"},
    {"kanji": "楽しみ","kana": "たのしみ","eng": "joy"},
    {"kanji": "楽しむ","kana": "たのしむ","eng": "to enjoy oneself"},
    {"kanji": "足りる","kana": "たりる","eng": "to be enough"},
    {"kanji": "力","kana": "ちから","eng": "strength, power"},
    {"kanji": "注意","kana": "ちゅうい","eng": "caution"},
    {"kanji": "中学校","kana": "ちゅうがっこう","eng": "junior high school, middle school"},
    {"kanji": "地理","kana": "ちり","eng": "geography"},
    {"kanji": "店員","kana": "てんいん","eng": "shop assistant"},
    {"kanji": "通る","kana": "とおる","eng": "to go through"},
    {"kanji": "特に","kana": "とくに","eng": "particularly, especially"},
    {"kanji": "特別","kana": "とくべつ","eng": "special"},
    {"kanji": "特急","kana": "とっきゅう","eng": "limited express train (faster than an express train)"},
    {"kanji": "止める","kana": "とめる, やめる, とどめる","eng": "to stop something"},
    {"kanji": "中々","kana": "なかなか","eng": "considerably"},
    {"kanji": "座る","kana": "すわる","eng": "to sit; to squat, to assume (a position), to hold steady; to hold still"},
    {"kanji": "入学","kana": "にゅうがく","eng": "to enter school or university"},
    {"kanji": "運ぶ","kana": "はこぶ","eng": "to transport"},
    {"kanji": "始める","kana": "はじめる","eng": "to begin"},
    {"kanji": "発音","kana": "はつおん","eng": "pronunciation"},
    {"kanji": "花見","kana": "はなみ","eng": "cherry-blossom viewing"},
    {"kanji": "日","kana": "ひ, にち","eng": "day, sun"},
    {"kanji": "火","kana": "ひ","eng": "fire"},
    {"kanji": "開く","kana": "ひらく, あく","eng": "to open an event"},
    {"kanji": "昼間","kana": "ひるま","eng": "daytime, during the day"},
    {"kanji": "昼休み","kana": "ひるやすみ","eng": "noon break"},
    {"kanji": "文学","kana": "ぶんがく","eng": "literature"},
    {"kanji": "別","kana": "べつ","eng": "different"},
    {"kanji": "差す","kana": "さす","eng": "to shine, to be visible, to be tinged with, to rise (of water levels); to flow in, to be felt (i.e. as an emotion); to come over one, to hold up (an umbrella, etc.)"},
    {"kanji": "咲く","kana": "さく","eng": "to bloom"},
    {"kanji": "見つかる","kana": "みつかる","eng": "to be discovered"},
    {"kanji": "見つける","kana": "みつける","eng": "to discover"},
    {"kanji": "止む","kana": "やむ","eng": "to stop"},
    {"kanji": "用","kana": "よう","eng": "use"},
    {"kanji": "用意","kana": "ようい","eng": "preparation"},
    {"kanji": "用事","kana": "ようじ","eng": "things to do"},
    {"kanji": "旅館","kana": "りょかん","eng": "Japanese hotel"},
    {"kanji": "別れる","kana": "わかれる","eng": "to separate"},
    {"kanji": "会う","kana": "あう","eng": "to meet"},
    {"kanji": "吹く","kana": "ふく","eng": "to blow (e.g. wind); to play a wind instrument, to emit; to spout, to whistle, to laugh; to burst into laughter, to smelt; to mint, to brag; to talk big"},
    {"kanji": "吸う","kana": "すう","eng": "to smoke; to breathe in; to inhale, to suck; to sip; to slurp, to absorb; to soak up, to kiss"},
    {"kanji": "明い","kana": "あかるい","eng": "bright"},
    {"kanji": "切符","kana": "きっぷ","eng": "ticket"},
    {"kanji": "開ける","kana": "あける","eng": "to open"},
    {"kanji": "朝","kana": "あさ","eng": "morning"},
    {"kanji": "足","kana": "あし","eng": "foot, leg"},
    {"kanji": "新しい","kana": "あたらしい","eng": "new"},
    {"kanji": "橋","kana": "はし","eng": "bridge"},
    {"kanji": "姉","kana": "あね","eng": "(humble) older sister"},
    {"kanji": "歯","kana": "は","eng": "tooth, (one's) age"},
    {"kanji": "首","kana": "くび, こうべ","eng": "neck, head, dismissal; discharge; firing (from a job)"},
    {"kanji": "医者","kana": "いしゃ","eng": "medical doctor"},
    {"kanji": "飛行場","kana": "ひこうじょう","eng": "airfield; airport"},
    {"kanji": "意味","kana": "いみ","eng": "meaning"},
    {"kanji": "集まる","kana": "あつまる","eng": "to gather; to collect; to assemble"},
    {"kanji": "入口","kana": "いりぐち","eng": "entrance"},
    {"kanji": "色","kana": "いろ","eng": "colour"},
    {"kanji": "降り出す","kana": "ふりだす","eng": "to begin to rain; to begin to snow"},
    {"kanji": "間に合う","kana": "まにあう","eng": "to be in time for, to serve (suit, meet) the purpose; to be good enough; to be enough"},
    {"kanji": "金持ち","kana": "かねもち","eng": "rich person"},
    {"kanji": "部長","kana": "ぶちょう","eng": "head (chief, director) of a section or department, head of a (school) club; head of a (school) team"},
    {"kanji": "上着","kana": "うわぎ","eng": "jacket"},
    {"kanji": "選ぶ","kana": "えらぶ","eng": "to choose; to select"},
    {"kanji": "映画館","kana": "えいがかん","eng": "cinema"},
    {"kanji": "遊び","kana": "あそび","eng": "playing, play (margin between on and off, gap before pressing button or lever has an effect)"},
    {"kanji": "遅れる","kana": "おくれる","eng": "to be late; to be delayed; to fall behind schedule; to be overdue"},
    {"kanji": "多い","kana": "おおい","eng": "many"},
    {"kanji": "起きる","kana": "おきる","eng": "to get up"},
    {"kanji": "教える","kana": "おしえる","eng": "to teach, to tell"},
    {"kanji": "進む","kana": "すすむ","eng": "to advance; to go forward, to precede; to go ahead (of), to make progress; to improve, to deepen; to heighten, to be fast (of a clock); to be ahead, to do of one's own free will, to grow wild"},
    {"kanji": "弟","kana": "おとうと","eng": "younger brother"},
    {"kanji": "同じ","kana": "おなじ","eng": "same"},
    {"kanji": "連絡","kana": "れんらく","eng": "to contact; to get in touch, contacting; getting in touch; communication; call; message, connection; coordination; junction, intercalary; intercalaris; internuncial"},
    {"kanji": "込む","kana": "こむ","eng": "to be crowded; to be packed, to be complex, to go into; to put into; to remain (seated); to be plunged into (silence); to do thoroughly, to do intently, to continue in the same state"},
    {"kanji": "重い","kana": "おもい","eng": "Heavy"},
    {"kanji": "終わる","kana": "おわる","eng": "to finish"},
    {"kanji": "音楽","kana": "おんがく","eng": "Music"},
    {"kanji": "会社","kana": "かいしゃ","eng": "Company"},
    {"kanji": "買い物","kana": "かいもの","eng": "Shopping"},
    {"kanji": "踊る","kana": "おどる","eng": "to dance (orig. a hopping dance)"},
    {"kanji": "踊り","kana": "おどり","eng": "dance"},
    {"kanji": "貸す","kana": "かす","eng": "to lend"},
    {"kanji": "趣味","kana": "しゅみ","eng": "hobby; pastime, tastes; preference; liking"},
    {"kanji": "家族","kana": "かぞく","eng": "Family"},
    {"kanji": "方","kana": "かた, ほう","eng": "person, way of doing"},
    {"kanji": "紙","kana": "かみ","eng": "paper"},
    {"kanji": "林","kana": "はやし","eng": "woods; forest; copse; thicket, bunch; line (of something); collection"},
    {"kanji": "体","kana": "からだ, てい","eng": "Body"},
    {"kanji": "借りる","kana": "かりる","eng": "to borrow"},
    {"kanji": "漢字","kana": "かんじ","eng": "Chinese character"},
    {"kanji": "切手","kana": "きって","eng": "postage stamp"},
    {"kanji": "牛肉","kana": "ぎゅうにく","eng": "Beef"},
    {"kanji": "教室","kana": "きょうしつ","eng": "Classroom"},
    {"kanji": "兄弟","kana": "きょうだい","eng": "(humble) siblings"},
    {"kanji": "去年","kana": "きょねん","eng": "last year"},
    {"kanji": "切る","kana": "きる","eng": "to cut"},
    {"kanji": "着る","kana": "きる","eng": "to put on from the shoulders down"},
    {"kanji": "銀行","kana": "ぎんこう","eng": "Bank"},
    {"kanji": "赤んぼう","kana": "あかんぼう","eng": "baby; infant"},
    {"kanji": "負ける","kana": "まける","eng": "to lose; to be defeated, to succumb; to give in; to surrender; to yield, to be inferior to, to break out in a rash due to (e.g. lacquer, shaving, etc.), to reduce the price"},
    {"kanji": "黒","kana": "くろ","eng": "Black"},
    {"kanji": "黒い","kana": "くろい","eng": "black"},
    {"kanji": "今朝","kana": "けさ","eng": "this morning"},
    {"kanji": "月曜日","kana": "げつようび","eng": "Monday"},
    {"kanji": "課長","kana": "かちょう","eng": "section manager; section chief"},
    {"kanji": "説明","kana": "せつめい","eng": "explanation; exposition"},
    {"kanji": "今週","kana": "こんしゅう","eng": "this week"},
    {"kanji": "魚","kana": "さかな, うお","eng": "Fish"},
    {"kanji": "作文","kana": "さくぶん","eng": "composition, writing"},
    {"kanji": "試合","kana": "しあい","eng": "match; game; bout; contest"},
    {"kanji": "質問","kana": "しつもん","eng": "Question"},
    {"kanji": "自転車","kana": "じてんしゃ","eng": "Bicycle"},
    {"kanji": "自動車","kana": "じどうしゃ","eng": "Automobile"},
    {"kanji": "死ぬ","kana": "しぬ","eng": "to die"},
    {"kanji": "写真","kana": "しゃしん","eng": "photograph"},
    {"kanji": "上手","kana": "じょうず, うわて","eng": "Skillful"},
    {"kanji": "食堂","kana": "しょくどう","eng": "dining hall"},
    {"kanji": "知る","kana": "しる","eng": "to know"},
    {"kanji": "新聞","kana": "しんぶん","eng": "newspaper"},
    {"kanji": "触る","kana": "さわる","eng": "to touch; to feel"},
    {"kanji": "少ない","kana": "すくない","eng": "a few"},
    {"kanji": "裏","kana": "うら","eng": "bottom (or another side that is hidden from view); undersurface; opposite side; reverse side, rear; back; behind (the house), lining; inside, out of sight; behind the scenes"},
    {"kanji": "住む","kana": "すむ","eng": "to live in"},
    {"kanji": "先週","kana": "せんしゅう","eng": "last week"},
    {"kanji": "空","kana": "そら, から","eng": "sky (そら), emptiness (から)"},
    {"kanji": "大使館","kana": "たいしかん","eng": "embassy"},
    {"kanji": "大切","kana": "たいせつ","eng": "important"},
    {"kanji": "立つ","kana": "たつ","eng": "to stand"},
    {"kanji": "建物","kana": "たてもの","eng": "building"},
    {"kanji": "楽しい","kana": "たのしい","eng": "enjoyable"},
    {"kanji": "血","kana": "ち","eng": "blood; consanguinity"},
    {"kanji": "近い","kana": "ちかい","eng": "near"},
    {"kanji": "近く","kana": "ちかく","eng": "near"},
    {"kanji": "地図","kana": "ちず","eng": "map"},
    {"kanji": "茶色","kana": "ちゃいろ","eng": "brown"},
    {"kanji": "使う","kana": "つかう","eng": "to use"},
    {"kanji": "着く","kana": "つく","eng": "to arrive at"},
    {"kanji": "作る","kana": "つくる","eng": "to make"},
    {"kanji": "強い","kana": "つよい","eng": "powerful"},
    {"kanji": "虫","kana": "むし","eng": "insect; bug; cricket; moth; worm"},
    {"kanji": "手紙","kana": "てがみ","eng": "letter"},
    {"kanji": "出口","kana": "でぐち","eng": "exit"},
    {"kanji": "動物","kana": "どうぶつ","eng": "animal"},
    {"kanji": "時計","kana": "とけい","eng": "watch, clock"},
    {"kanji": "図書館","kana": "としょかん","eng": "library"},
    {"kanji": "葉","kana": "は","eng": "leaf, counter for leaves, pieces of paper, etc., counter for boats"},
    {"kanji": "落ちる","kana": "おちる","eng": "to fall down; to drop; to fall (e.g. rain); to sink (e.g. sun or moon); to fall onto (e.g. light or one's gaze); to be used in a certain place (e.g. money), to be omitted"},
    {"kanji": "鳥","kana": "とり","eng": "bird"},
    {"kanji": "とり肉","kana": "とりにく","eng": "chicken meat"},
    {"kanji": "落とす","kana": "おとす","eng": "to drop; to lose; to let fall; to shed (light); to cast (one's gaze); to pour in (liquid); to leave behind, to clean off (dirt, makeup, paint, etc.); to remove (e.g. stains or facial hair)"},
    {"kanji": "夏休み","kana": "なつやすみ","eng": "summer holiday"},
    {"kanji": "習う","kana": "ならう","eng": "to learn"},
    {"kanji": "草","kana": "くさ","eng": "grass; weed; herb; thatch, ninja, not genuine; substandard, laughter; LOL, draft; rough copy, cursive script; \"grass\" kanji"},
    {"kanji": "船","kana": "ふね","eng": "ship; boat; watercraft; vessel; steamship, tank; tub; vat; trough, counter for boat-shaped containers (e.g. of sashimi)"},
    {"kanji": "興味","kana": "きょうみ","eng": "interest (in something); curiosity (about something); zest (for)"},
    {"kanji": "腕","kana": "うで","eng": "arm, skill; efforts; ability, arm (esp. upper arm), counter used to measure the thickness of round objects"},
    {"kanji": "始まる","kana": "はじまる","eng": "to begin"},
    {"kanji": "始め","kana": "はじめ","eng": "beginning"},
    {"kanji": "背中","kana": "せなか","eng": "back (of body)"},
    {"kanji": "花","kana": "はな","eng": "flower"},
    {"kanji": "早い","kana": "はやい","eng": "early"},
    {"kanji": "美しい","kana": "うつくしい","eng": "beautiful; lovely"},
    {"kanji": "病院","kana": "びょういん","eng": "hospital"},
    {"kanji": "病気","kana": "びょうき","eng": "illness"},
    {"kanji": "昼","kana": "ひる","eng": "noon, daytime"},
    {"kanji": "広い","kana": "ひろい","eng": "spacious, wide"},
    {"kanji": "服","kana": "ふく","eng": "clothes"},
    {"kanji": "線","kana": "せん","eng": "line; stripe; stria, line (e.g. telephone line); wire, ray (e.g. X-ray); beam, line (e.g. of a railroad); track; route; lane, outline; contours; form, level, division, line (of action)"},
    {"kanji": "古い","kana": "ふるい","eng": "old (not used for people)"},
    {"kanji": "下手","kana": "へた","eng": "unskillful"},
    {"kanji": "勉強","kana": "べんきょう","eng": "to study"},
    {"kanji": "毎朝","kana": "まいあさ","eng": "every morning"},
    {"kanji": "毎週","kana": "まいしゅう","eng": "every week"},
    {"kanji": "町","kana": "まち","eng": "town, city"},
    {"kanji": "待つ","kana": "まつ","eng": "to wait"},
    {"kanji": "続ける","kana": "つづける","eng": "to continue; to keep up; to keep on"},
    {"kanji": "続く","kana": "つづく","eng": "to continue; to last; to go on, to continue (without a break); to be unbroken, to occur again and again, to lead to; to connect to; to adjoin, to come after; to follow"},
    {"kanji": "紹介","kana": "しょうかい","eng": "introduction; presentation; referral; listing"},
    {"kanji": "もう一度","kana": "もういちど","eng": "again"},
    {"kanji": "約束","kana": "やくそく","eng": "promise; agreement; arrangement; one's word; contract; pact; appointment; engagement; date, convention; rule, destiny; fate"},
    {"kanji": "持つ","kana": "もつ","eng": "to hold"},
    {"kanji": "物","kana": "もの","eng": "thing"},
    {"kanji": "問題","kana": "もんだい","eng": "problem"},
    {"kanji": "森","kana": "もり","eng": "forest, shrine grove"},
    {"kanji": "簡単","kana": "かんたん","eng": "simple; easy; uncomplicated, brief; quick; light"},
    {"kanji": "夕方","kana": "ゆうがた","eng": "evening"},
    {"kanji": "夕飯","kana": "ゆうはん","eng": "dinner"},
    {"kanji": "有名","kana": "ゆうめい","eng": "famous"},
    {"kanji": "洋服","kana": "ようふく","eng": "western-style clothes"},
    {"kanji": "夜","kana": "よる, よ","eng": "evening, night"},
    {"kanji": "来週","kana": "らいしゅう","eng": "next week"},
    {"kanji": "料理","kana": "りょうり","eng": "cuisine"},
    {"kanji": "旅行","kana": "りょこう","eng": "travel"},
    {"kanji": "悪い","kana": "わるい, にくい","eng": "bad"},
    {"kanji": "お礼","kana": "おれい","eng": "thanks; gratitude, manners; etiquette, bow, reward; gift, ceremony; ritual"},
    {"kanji": "お祝い","kana": "おいわい","eng": "congratulation; congratulations; celebration; festival; congratulatory gift"},
    {"kanji": "お祭り","kana": "おまつり","eng": "festival; feast; carnival"},
    {"kanji": "ご主人","kana": "ごしゅじん","eng": "your husband; her husband"},
    {"kanji": "答え","kana": "こたえ","eng": "answer; reply; response; solution"},
    {"kanji": "笑う","kana": "わらう","eng": "to laugh, to smile, to sneer; to ridicule, to be dumbfounded; to be flabbergasted"},
    {"kanji": "星","kana": "ほし","eng": "star; any light-emitting (or reflecting) heavenly body (except for the sun and the moon), offender; perpetrator, star point (in go); hoshi; intersection marked with a dot, circular symbol (said to be shaped like a shining star), bullseye, one's star (out of the nine stars)"},
    {"kanji": "上がる","kana": "あがる","eng": "to rise; to go up; to come up; to ascend; to be raised, to enter (esp. from outdoors); to come in; to go in, to enter (a school); to advance to the next grade, to get out (of water)"},
    {"kanji": "石","kana": "いし","eng": "stone, gem; jewel, measure of volume (approx. 180.39 liters, 6.37 cub. ft.), measure of a Japanese-style boat's loading capacity (approx. 278.26 liters)"},
    {"kanji": "眠る","kana": "ねむる","eng": "to sleep (not necessarily lying down), to die, to lie idle (e.g. of resources); to be dormant; to be unused, to close one's eyes"},
    {"kanji": "眠い","kana": "ねむい","eng": "sleepy; drowsy; somnolent"},
    {"kanji": "久しぶり","kana": "ひさしぶり","eng": "a long time (since the last time); it's been a while (since I last saw, mailed, etc., you)"},
    {"kanji": "乗り物","kana": "のりもの","eng": "vehicle; conveyance; transport, ride (playground, fair, carnival); playground facility"},
    {"kanji": "真ん中","kana": "まんなか","eng": "middle; centre; center; mid-way"},
    {"kanji": "事故","kana": "じこ","eng": "accident; incident; trouble, circumstances; reasons"},
    {"kanji": "二階建て","kana": "にかいだて","eng": "two-storied building"},
    {"kanji": "皆","kana": "みな, みんな","eng": "all; everyone; everybody, everything"},
    {"kanji": "交通","kana": "こうつう","eng": "traffic; transportation; communication; exchange (of ideas, etc.); intercourse"},
    {"kanji": "番組","kana": "ばんぐみ","eng": "program (e.g. TV); programme"},
    {"kanji": "生活","kana": "せいかつ","eng": "living; life (one's daily existence); livelihood"},
    {"kanji": "伝える","kana": "つたえる","eng": "to convey; to report; to transmit; to communicate; to tell; to impart; to propagate; to teach; to bequeath"},
    {"kanji": "似る","kana": "にる","eng": "to resemble; to look like; to take after, to be similar (in status, condition, etc.); to be close; to be alike; to be like"},
    {"kanji": "片付ける","kana": "かたづける","eng": "to tidy up; to put in order; to straighten up; to put away, to settle (problem); to clear (dispute), to finish; to bring something to an end, to marry off (e.g. a daughter), to do away with someone"},
    {"kanji": "点","kana": "てん","eng": "dot; point; mark, gidayuu musicians (in kabuki), spot; mark, point; dot, mark (e.g. in exam); score; points, comma, aspect; matter; respect, counter for goods, items, articles of clothing, works of art, etc., dot"},
    {"kanji": "漫画","kana": "まんが","eng": "cartoon; comic; comic strip"},
    {"kanji": "優しい","kana": "やさしい","eng": "tender; kind; gentle; graceful; affectionate; amiable"},
    {"kanji": "先輩","kana": "せんぱい","eng": "senior (at work or school); superior; elder; older graduate; progenitor; old-timer"},
    {"kanji": "光","kana": "ひかり","eng": "light, illumination; ray; beam; gleam; glow, happiness; hope, influence; power, vision; eyesight"},
    {"kanji": "光る","kana": "ひかる","eng": "to shine; to glitter; to be bright"},
    {"kanji": "具合","kana": "ぐあい","eng": "condition; state; manner; health"},
    {"kanji": "内","kana": "うち","eng": "inside; within, while, among; amongst; between, we (referring to one's in-group, e.g. company, etc.); our, my spouse, imperial palace grounds, emperor, I (primarily used by women and children)"},
    {"kanji": "冷たい","kana": "つめたい","eng": "cold (to the touch); chilly; icy; freezing, coldhearted; unfeeling"},
    {"kanji": "湯","kana": "ゆ","eng": "hot water, hot bath; hot spring, molten iron, soup"},
    {"kanji": "動物園","kana": "どうぶつえん","eng": "zoo; zoological gardens"},
    {"kanji": "勝つ","kana": "かつ","eng": "to win; to gain victory"},
    {"kanji": "包む","kana": "つつむ, くるむ","eng": "to wrap up; to tuck in; to pack; to do up; to cover with; to dress in, to conceal; to hide; to be engulfed in; to be enveloped by, to wrap up; to tuck in; to pack"},
    {"kanji": "十分","kana": "じゅうぶん, じゅっぷん, じっぷん","eng": "10 minutes, plenty; enough; sufficient; satisfactory; adequate, division into ten, perfectly; thoroughly; fully; in full"},
    {"kanji": "卒業","kana": "そつぎょう","eng": "graduation; completion (e.g. of a course), outgrowing something; moving on"},
    {"kanji": "危険","kana": "きけん","eng": "danger; peril; hazard, risk"},
    {"kanji": "受ける","kana": "うける","eng": "to receive; to get, to catch (e.g. a ball), to be struck by (wind, waves, sunlight, etc.), to sustain (damage); to incur (a loss); to suffer (an injury); to feel (influence), to undergo (e.g. surgery)"},
    {"kanji": "湖","kana": "みずうみ","eng": "lake"},
    {"kanji": "普通","kana": "ふつう","eng": "general; ordinary; usual, normally; generally; usually, local train; train that stops at every station"},
    {"kanji": "合う","kana": "あう","eng": "to come together; to merge; to unite; to meet, to fit; to match; to suit; to agree with; to be correct, to be profitable; to be equitable, to do ... to each other"},
    {"kanji": "向かう","kana": "むかう","eng": "to face, to go towards; to head towards"},
    {"kanji": "君","kana": "きみ","eng": "you; buddy; pal, monarch; ruler; sovereign; (one's) master, Mr (junior); master; boy, suffix appended to somebody else's family members, you"},
    {"kanji": "周り","kana": "まわり","eng": "circumference; girth, surroundings; neighbourhood; neighborhood; vicinity"},
    {"kanji": "困る","kana": "こまる","eng": "to be troubled; to be worried; to be bothered; to be embarrassed; to be stumped"},
    {"kanji": "固い","kana": "かたい","eng": "hard; solid; tough, stiff; tight; wooden; unpolished (e.g. writing), strong; firm (not viscous or easily moved), safe; steady; honest; steadfast, obstinate; stubborn, bookish"},
    {"kanji": "地震","kana": "じしん","eng": "earthquake"},
    {"kanji": "坂","kana": "さか","eng": "slope; hill"},
    {"kanji": "深い","kana": "ふかい","eng": "deep, profound, dense; thick, close (relationship), intense; strong, late"},
    {"kanji": "場所","kana": "ばしょ","eng": "place; location; spot; position, room; space, basho; wrestling tournament"},
    {"kanji": "消しゴム","kana": "けしごむ","eng": "eraser; India rubber"},
    {"kanji": "声","kana": "こえ","eng": "voice"},
    {"kanji": "変","kana": "へん","eng": "strange; odd; peculiar; weird; curious; queer; eccentric; funny; suspicious; fishy, unexpected, change, incident; disturbance; disaster; accident, flat"},
    {"kanji": "変える","kana": "かえる","eng": "to change; to alter; to transform; to convert; to turn; to vary, to reform; to revise; to amend"},
    {"kanji": "変わる","kana": "かわる","eng": "to change; to be transformed; to be altered; to vary, to move to, to be different; to be uncommon; to be unusual"},
    {"kanji": "夢","kana": "ゆめ","eng": "dream"},
    {"kanji": "太る","kana": "ふとる","eng": "to grow fat (stout, plump); to become fat; to gain weight"},
    {"kanji": "泣く","kana": "なく","eng": "to cry; to weep; to sob; to howl"},
    {"kanji": "娘","kana": "むすめ","eng": "(my) daughter, girl (i.e. a young, unmarried woman)"},
    {"kanji": "安全","kana": "あんぜん","eng": "safety, security"},
    {"kanji": "客","kana": "きゃく","eng": "guest; visitor, customer; client; shopper; spectator; audience; tourist; sightseer; passenger, visitor from afar; guest, visitor from afar, joy-bringing spirit from the divine realms"},
    {"kanji": "寺","kana": "てら","eng": "temple (Buddhist), counter for temples"},
    {"kanji": "将来","kana": "しょうらい","eng": "future (usually near); prospects"},
    {"kanji": "小説","kana": "しょうせつ","eng": "novel; (short) story"},
    {"kanji": "届ける","kana": "とどける","eng": "to deliver; to forward; to send, to report; to notify; to file notice (to the authorities); to give notice; to register"},
    {"kanji": "島","kana": "しま","eng": "island, territory (of a prostitute, organized crime gang, etc.); turf, Island, insula; island; islet"},
    {"kanji": "泊まる","kana": "とまる","eng": "to stay at (e.g. hotel), to be docked; to be berthed; to be moored"},
    {"kanji": "決める","kana": "きめる","eng": "to decide; to choose; to determine; to make up one's mind; to resolve; to set one's heart on; to settle; to arrange; to set; to appoint; to fix, to clinch (a victory)"},
    {"kanji": "布団","kana": "ふとん","eng": "futon (quilted Japanese-style mattress laid out on the floor), round cushion used for Zen meditation (traditionally made of woven bulrush leaves)"},
    {"kanji": "席","kana": "せき","eng": "seat, location (of a gathering, etc.); place, position; post, woven mat (esp. one made of straw), seat"},
    {"kanji": "引き出し","kana": "ひきだし","eng": "drawer, withdrawal; drawing out, variety of knowledge and experience useful for handling things impromptu"},
    {"kanji": "決まる","kana": "きまる","eng": "to be decided; to be settled, to look good in (clothes)"},
    {"kanji": "気分","kana": "きぶん","eng": "feeling; mood"},
    {"kanji": "役に立つ","kana": "やくにたつ","eng": "to be helpful; to be useful"},
    {"kanji": "彼","kana": "かれ","eng": "that (indicating something distant from both speaker and listener (in space, time or psychologically), or something understood without naming it directly), that person (used to refer to one's equals or inferiors), over there, down there (i.e. one's genitals), period"},
    {"kanji": "彼女","kana": "かのじょ","eng": "she; her, her, girlfriend; sweetheart"},
    {"kanji": "復習","kana": "ふくしゅう","eng": "review; revision"},
    {"kanji": "忘れ物","kana": "わすれもの","eng": "lost article; something forgotten"},
    {"kanji": "怒る","kana": "おこる, いかる","eng": "to get angry; to get mad, to tell someone off; to scold, to be angular; to be square"},
    {"kanji": "怖い","kana": "こわい","eng": "scary; frightening; eerie; dreadful, (I'm) afraid"},
    {"kanji": "恥ずかしい","kana": "はずかしい","eng": "shy; ashamed; embarrassed, disgraceful; shameful"},
    {"kanji": "息子","kana": "むすこ","eng": "son"},
    {"kanji": "悲しい","kana": "かなしい","eng": "sad; sorrowful"},
    {"kanji": "毛","kana": "け, もう","eng": "hair, fur; wool, down; plumage; feathers, one-thousandth; 0.03 mm (one-thousandth of a sun); 0.01 percent (one-thousandth of a wari); 3.75 milligrams (one-thousandth of a monme), old monetary unit (0.0001 yen)"},
    {"kanji": "残る","kana": "のこる","eng": "to remain; to be left"},
    {"kanji": "戻る","kana": "もどる","eng": "to turn back (e.g. half-way), to return; to go back, to recover (e.g. something lost); to be returned, to rebound; to spring back, to go against; to act contrary to"},
    {"kanji": "手伝う","kana": "てつだう","eng": "to help; to assist; to aid, to contribute to; to be a factor in"},
    {"kanji": "手袋","kana": "てぶくろ","eng": "glove; mitten; mitt"},
    {"kanji": "打つ","kana": "うつ, ぶつ","eng": "to hit; to strike; to knock; to beat; to punch; to slap; to tap; to bang; to clap; to pound, to strike (noon, etc.); to sound (cymbals, etc.); to beat (a drum, etc.), to beat (rhythmically, e.g. pulse, waves, etc.), to move"},
    {"kanji": "払う","kana": "はらう","eng": "to pay (e.g. money, bill), to brush off; to wipe away; to clear away; to dust off; to cut off (e.g. branches), to drive away (e.g. one's competitors), to sell off (something unneeded)"},
    {"kanji": "押し入れ","kana": "おしいれ","eng": "closet"},
    {"kanji": "拾う","kana": "ひろう","eng": "to pick up; to find; to gather"},
    {"kanji": "指","kana": "ゆび","eng": "finger; toe; digit, between (e.g. two people); face to face, hindrance; impediment, arrhythmic section of recitative in noh music, prefix used for stress or emphasis, counter for traditional dance songs"},
    {"kanji": "指輪","kana": "ゆびわ","eng": "(finger) ring"},
    {"kanji": "探す","kana": "さがす","eng": "to search (for something desired, needed); to look for, to search (for something lost); to seek (a suspect in a crime)"},
    {"kanji": "故障","kana": "こしょう","eng": "breakdown; failure; fault; accident; out of order, damage; hurt, objection; protest"},
    {"kanji": "歴史","kana": "れきし","eng": "history"},
    {"kanji": "数学","kana": "すうがく","eng": "mathematics; arithmetic"},
    {"kanji": "文化","kana": "ぶんか","eng": "culture; civilization; civilisation, Bunka era (1804.2.11-1818.4.22)"},
    {"kanji": "机","kana": "つくえ","eng": "desk"},
    {"kanji": "日記","kana": "にっき","eng": "diary; journal"}
];