export const n5 = [
    {"kanji": "駅","kana": "えき","eng": "station"},
    {"kanji": "後","kana": "あと, ご, のち","eng": "afterwards"},
    {"kanji": "雨","kana": "あめ","eng": "rain"},
    {"kanji": "行く","kana": "いく, ゆく","eng": "to go"},
    {"kanji": "一","kana": "いち","eng": "one"},
    {"kanji": "一日","kana": "いちにち, ついたち","eng": "one day (いちにち), first of the month (ついたち)"},
    {"kanji": "五日","kana": "いつか","eng": "five days, fifth day"},
    {"kanji": "五つ","kana": "いつつ","eng": "five"},
    {"kanji": "今","kana": "いま","eng": "now"},
    {"kanji": "入れる","kana": "いれる","eng": "to put in"},
    {"kanji": "上","kana": "うえ, かみ, じょう","eng": "on top of"},
    {"kanji": "後ろ","kana": "うしろ","eng": "behind"},
    {"kanji": "生まれる","kana": "うまれる","eng": "to be born"},
    {"kanji": "大きい","kana": "おおきい","eng": "big"},
    {"kanji": "大きな","kana": "おおきな","eng": "big"},
    {"kanji": "お母さん","kana": "おかあさん","eng": "(honorable) mother"},
    {"kanji": "お金","kana": "おかね","eng": "money"},
    {"kanji": "お父さん","kana": "おとうさん","eng": "(honorable) father"},
    {"kanji": "男","kana": "おとこ","eng": "Man"},
    {"kanji": "男の子","kana": "おとこのこ","eng": "Boy"},
    {"kanji": "大人","kana": "おとな","eng": "Adult"},
    {"kanji": "女","kana": "おんな","eng": "Woman"},
    {"kanji": "女の子","kana": "おんなのこ","eng": "Girl"},
    {"kanji": "外国","kana": "がいこく","eng": "foreign country"},
    {"kanji": "外国人","kana": "がいこくじん","eng": "Foreigner"},
    {"kanji": "書く","kana": "かく","eng": "to write"},
    {"kanji": "学生","kana": "がくせい","eng": "Student"},
    {"kanji": "学校","kana": "がっこう","eng": "School"},
    {"kanji": "川","kana": "かわ","eng": "River"},
    {"kanji": "木","kana": "き","eng": "tree, wood"},
    {"kanji": "聞く","kana": "きく","eng": "to hear, to listen to, to ask"},
    {"kanji": "北","kana": "きた","eng": "North"},
    {"kanji": "九","kana": "きゅう, く","eng": "Nine"},
    {"kanji": "今日","kana": "きょう","eng": "Today"},
    {"kanji": "国","kana": "くに","eng": "Country"},
    {"kanji": "来る","kana": "くる, きたる","eng": "to come"},
    {"kanji": "車","kana": "くるま","eng": "car, vehicle"},
    {"kanji": "五","kana": "ご","eng": "Five"},
    {"kanji": "午後","kana": "ごご","eng": "afternoon"},
    {"kanji": "九日","kana": "ここのか","eng": "nine days, ninth day"},
    {"kanji": "九つ","kana": "ここのつ","eng": "Nine"},
    {"kanji": "午前","kana": "ごぜん","eng": "morning"},
    {"kanji": "今年","kana": "ことし","eng": "this year"},
    {"kanji": "今月","kana": "こんげつ","eng": "this month"},
    {"kanji": "先","kana": "さき","eng": "the future, previous"},
    {"kanji": "八円","kana": "はちえん","eng": "eight yen"},
    {"kanji": "三","kana": "さん","eng": "Three"},
    {"kanji": "四","kana": "よん, し","eng": "Four"},
    {"kanji": "時間","kana": "じかん","eng": "Time"},
    {"kanji": "下","kana": "した, げ, しも","eng": "Below"},
    {"kanji": "七","kana": "しち, なな","eng": "Seven"},
    {"kanji": "十","kana": "じゅう, とお","eng": "Ten"},
    {"kanji": "白","kana": "しろ","eng": "White"},
    {"kanji": "白い","kana": "しろい","eng": "White"},
    {"kanji": "千","kana": "せん","eng": "Thousand"},
    {"kanji": "先月","kana": "せんげつ","eng": "last month"},
    {"kanji": "先生","kana": "せんせい","eng": "teacher, doctor"},
    {"kanji": "外","kana": "そと, ほか","eng": "Outside"},
    {"kanji": "大学","kana": "だいがく","eng": "university"},
    {"kanji": "高い","kana": "たかい","eng": "tall, expensive"},
    {"kanji": "出す","kana": "だす","eng": "to put out"},
    {"kanji": "食べる","kana": "たべる","eng": "to eat"},
    {"kanji": "小さい","kana": "ちいさい","eng": "little"},
    {"kanji": "小さな","kana": "ちいさな","eng": "little"},
    {"kanji": "出かける","kana": "でかける","eng": "to go out"},
    {"kanji": "出る","kana": "でる","eng": "to appear, to leave"},
    {"kanji": "天気","kana": "てんき","eng": "weather"},
    {"kanji": "電気","kana": "でんき","eng": "electricity, electric light"},
    {"kanji": "電車","kana": "でんしゃ","eng": "electric train"},
    {"kanji": "電話","kana": "でんわ","eng": "telephone"},
    {"kanji": "十日","kana": "とおか","eng": "ten days, the tenth day"},
    {"kanji": "時々","kana": "ときどき","eng": "sometimes"},
    {"kanji": "年","kana": "とし, ねん","eng": "year"},
    {"kanji": "中","kana": "なか, ちゅう","eng": "middle"},
    {"kanji": "長い","kana": "ながい","eng": "long"},
    {"kanji": "七つ","kana": "ななつ","eng": "seven"},
    {"kanji": "七日","kana": "なのか","eng": "seven days, the seventh day"},
    {"kanji": "名前","kana": "なまえ","eng": "name"},
    {"kanji": "何","kana": "なん, なに","eng": "what"},
    {"kanji": "二","kana": "に","eng": "two"},
    {"kanji": "西","kana": "にし","eng": "west"},
    {"kanji": "入る","kana": "はいる, いる","eng": "to enter, to contain"},
    {"kanji": "八","kana": "はち","eng": "eight"},
    {"kanji": "二十日","kana": "はつか","eng": "twenty days, twentieth"},
    {"kanji": "話","kana": "はなし","eng": "talk, story"},
    {"kanji": "話す","kana": "はなす","eng": "to speak"},
    {"kanji": "半","kana": "はん","eng": "half"},
    {"kanji": "東","kana": "ひがし, あずま","eng": "east"},
    {"kanji": "左","kana": "ひだり","eng": "left hand side"},
    {"kanji": "人","kana": "ひと","eng": "person"},
    {"kanji": "一つ","kana": "ひとつ","eng": "one"},
    {"kanji": "一月","kana": "ひとつき, いちがつ","eng": "one month, January"},
    {"kanji": "一人","kana": "ひとり","eng": "one person"},
    {"kanji": "百","kana": "ひゃく","eng": "hundred"},
    {"kanji": "二つ","kana": "ふたつ","eng": "two"},
    {"kanji": "二人","kana": "ふたり","eng": "two people"},
    {"kanji": "二日","kana": "ふつか","eng": "two days, second day of the month"},
    {"kanji": "本","kana": "ほん","eng": "book"},
    {"kanji": "飲む","kana": "のむ","eng": "to drink; to gulp; to swallow; to take (medicine), to smoke (tobacco), to engulf; to overwhelm, to keep down; to suppress, to accept (e.g. demand, condition), to make light of"},
    {"kanji": "毎日","kana": "まいにち","eng": "every day"},
    {"kanji": "飲み物","kana": "のみもの","eng": "drink; beverage"},
    {"kanji": "前","kana": "まえ","eng": "before"},
    {"kanji": "食べ物","kana": "たべもの","eng": "food"},
    {"kanji": "万","kana": "まん","eng": "ten thousand"},
    {"kanji": "右","kana": "みぎ","eng": "right side"},
    {"kanji": "水","kana": "みず","eng": "water"},
    {"kanji": "見せる","kana": "みせる","eng": "to show"},
    {"kanji": "三日","kana": "みっか","eng": "three days, third day of the month"},
    {"kanji": "三つ","kana": "みっつ","eng": "three"},
    {"kanji": "南","kana": "みなみ","eng": "south"},
    {"kanji": "見る","kana": "みる","eng": "to see, to watch"},
    {"kanji": "六日","kana": "むいか","eng": "six days, sixth day of the month"},
    {"kanji": "六つ","kana": "むっつ","eng": "six"},
    {"kanji": "休み","kana": "やすみ","eng": "rest, holiday"},
    {"kanji": "休む","kana": "やすむ","eng": "to rest"},
    {"kanji": "八つ","kana": "やっつ","eng": "eight"},
    {"kanji": "山","kana": "やま","eng": "mountain"},
    {"kanji": "八日","kana": "ようか","eng": "eight days, eighth day of the month"},
    {"kanji": "四日","kana": "よっか","eng": "four days, fouth day of the month"},
    {"kanji": "四つ","kana": "よっつ","eng": "four"},
    {"kanji": "読む","kana": "よむ","eng": "to read"},
    {"kanji": "来月","kana": "らいげつ","eng": "next month"},
    {"kanji": "来年","kana": "らいねん","eng": "next year"},
    {"kanji": "六","kana": "ろく","eng": "six"},
    {"kanji": "お兄さん","kana": "おにいさん","eng": "older brother; elder brother, (vocative) young man; buddy; fella; laddie"},
    {"kanji": "お姉さん","kana": "おねえさん","eng": "elder sister, (vocative) young lady, miss (referring to a waitress, etc.), ma'am (used by geisha to refer to their superiors), older girl (no relation)"},
    {"kanji": "お手洗い","kana": "おてあらい","eng": "toilet; restroom; lavatory; bathroom"},
    {"kanji": "お茶","kana": "おちゃ","eng": "tea (usu. green), tea break (at work), tea ceremony"},
    {"kanji": "風","kana": "かぜ, ふう","eng": "wind; breeze; draught; draft, manner; behaviour; behavior, cold; influenza, method; manner; way; style, appearance; air, tendency, folk song (genre of the Shi Jing), wind (one of the five elements)"},
    {"kanji": "乗る","kana": "のる","eng": "to get on (train, plane, bus, ship, etc.); to get in; to board; to take; to embark, to get on (e.g. a footstool); to step on; to jump on; to sit on; to mount, to reach"},
    {"kanji": "仕事","kana": "しごと","eng": "work; job; business; occupation; employment; vocation; task, work"},
    {"kanji": "雪","kana": "ゆき","eng": "snow"},
    {"kanji": "元気","kana": "げんき","eng": "lively; full of spirit; energetic; vigorous; vital; spirited, healthy; well; fit; in good health"},
    {"kanji": "兄","kana": "あに","eng": "elder brother; older brother"},
    {"kanji": "冬","kana": "ふゆ","eng": "winter"},
    {"kanji": "初めて","kana": "はじめて","eng": "for the first time, only after ... is it ...; only when ... do you ..."},
    {"kanji": "友達","kana": "ともだち","eng": "friend; companion"},
    {"kanji": "取る","kana": "とる","eng": "to take; to pick up; to harvest; to earn; to win; to choose, to steal, to eat; to have (a meal), to remove (one's glasses, etc.), to compete (in sumo, cards, etc.)"},
    {"kanji": "口","kana": "くち","eng": "mouth, opening; hole; gap; orifice, mouth (of a bottle); spout; nozzle; mouthpiece, gate; door; entrance; exit, speaking; speech; talk (i.e. gossip), taste; palate, mouth (to feed), opening (i.e. vacancy)"},
    {"kanji": "難しい","kana": "むずかしい","eng": "difficult; hard; troublesome; complicated; serious (disease, problem, etc.), fussy; particular; fastidious; hard to please; displeased, gloomy; glum; sullen; serious (look), dirty"},
    {"kanji": "土曜日","kana": "どようび","eng": "Saturday"},
    {"kanji": "売る","kana": "うる","eng": "to sell"},
    {"kanji": "夏","kana": "なつ","eng": "summer"},
    {"kanji": "閉まる","kana": "しまる","eng": "to be shut; to close; to be closed, to be locked, to tighten; to be tightened, to become sober; to become tense"},
    {"kanji": "好き","kana": "すき","eng": "liking; fondness; love"},
    {"kanji": "妹","kana": "いもうと","eng": "younger sister, darling (only of a woman); dear; honey; my betrothed, one's sister, friend"},
    {"kanji": "金曜日","kana": "きんようび","eng": "Friday"},
    {"kanji": "部屋","kana": "へや","eng": "room; chamber, apartment; flat; pad, stable"},
    {"kanji": "子","kana": "こ","eng": "child, young (animal), young woman; young geisha, offshoot, interest, new shares, player who is not a dealer (in cards, mahjong, etc.)"},
    {"kanji": "安い","kana": "やすい","eng": "cheap; inexpensive, calm; peaceful; quiet"},
    {"kanji": "家","kana": "いえ, うち","eng": "house; residence; dwelling, family; household, lineage; family name, house; home (one's own), (one's) family; (one's) household"},
    {"kanji": "寒い","kana": "さむい","eng": "cold (e.g. weather), uninteresting (esp. joke); lame; dull; weak; corny"},
    {"kanji": "少し","kana": "すこし","eng": "small quantity; little; few; something, little while, short distance"},
    {"kanji": "遠い","kana": "とおい","eng": "far; distant"},
    {"kanji": "帰る","kana": "かえる","eng": "to return; to come home; to go home; to go back, to leave, to get home; to get to home plate"},
    {"kanji": "店","kana": "みせ","eng": "store; shop; establishment; restaurant"},
    {"kanji": "道","kana": "みち","eng": "road; street; way; path; course; route; lane, distance; ways (e.g. \"a long ways\"), the way (of proper conduct, etc.); one's way; morals, teachings (esp. Confucian or Buddhist)"},
    {"kanji": "忘れる","kana": "わすれる","eng": "to forget; to leave carelessly; to be forgetful of; to forget about; to forget (an article)"},
    {"kanji": "忙しい","kana": "いそがしい","eng": "busy; occupied; hectic, restless; hurried; fidgety"},
    {"kanji": "遅い","kana": "おそい","eng": "slow, late (e.g. \"late at night\"), too late, dull; stupid"},
    {"kanji": "手","kana": "て","eng": "hand; arm, forepaw; foreleg, handle, hand; worker; help, trouble; care; effort, means; way; trick; move; technique; workmanship, hand; handwriting, kind; type; sort, one's hands"},
    {"kanji": "走る","kana": "はしる","eng": "to run, to travel (movement of vehicles); to drive, to hurry to, to retreat (from battle); to take flight, to run away from home, to elope, to tend heavily toward, to flash"},
    {"kanji": "赤ちゃん","kana": "あかちゃん","eng": "baby; infant"},
    {"kanji": "買う","kana": "かう","eng": "to buy; to purchase, to value; to have a high opinion, to stir; to provoke"},
    {"kanji": "日曜日","kana": "にちようび","eng": "Sunday"},
    {"kanji": "月曜日","kana": "げつようび","eng": "Monday"},
    {"kanji": "言葉","kana": "ことば","eng": "language; dialect, word; words; phrase; term; expression; remark, speech; (manner of) speaking"},
    {"kanji": "映画","kana": "えいが","eng": "movie; film"},
    {"kanji": "春","kana": "はる","eng": "spring; springtime, New Year, prime (of one's life, etc.), adolescence; puberty, sexuality"},
    {"kanji": "時","kana": "とき","eng": "time; hour; moment, occasion; case, chance; opportunity; season, the times; the age; the day, tense"},
    {"kanji": "月","kana": "つき, げつ","eng": "moon, month, month (of the year); used after number or question word (e.g. nan or nani), Monday"},
    {"kanji": "言う","kana": "いう, ゆう","eng": "to say; to utter; to declare, to name; to call, to go (e.g. \"the alarm went ping\"); to make a noise"},
    {"kanji": "木曜日","kana": "もくようび","eng": "Thursday"},
    {"kanji": "覚える","kana": "おぼえる","eng": "to memorize; to memorise; to commit to memory; to learn by heart; to bear in mind; to remember, to learn; to pick up; to acquire, to feel, to think; to regard"},
    {"kanji": "見える","kana": "みえる","eng": "to be seen; to be in sight, to look; to seem; to appear, to come, to have an audience; to meet; to see, to face (an enemy); to confront, to serve (esp. as one's wife)"},
    {"kanji": "歌","kana": "うた","eng": "song, classical Japanese poetry (esp. tanka), modern poetry"},
    {"kanji": "歌う","kana": "うたう","eng": "to sing, to sing (one's praises in a poem, etc.); to compose a poem; to recite a poem"},
    {"kanji": "止まる","kana": "とまる","eng": "to stop (moving); to come to a stop, to stop (doing, working, being supplied); to come to a halt; to cease; to be stopped; to be suspended, to alight; to perch on, to remain"},
    {"kanji": "歩く","kana": "あるく","eng": "to walk"},
    {"kanji": "英語","kana": "えいご","eng": "English (language)"},
    {"kanji": "母","kana": "はは","eng": "mother"},
    {"kanji": "水曜日","kana": "すいようび","eng": "Wednesday"},
    {"kanji": "洗う","kana": "あらう","eng": "to wash; to cleanse; to rinse, to inquire into; investigate, to purify (one's heart), to lave (e.g. shore); to wash over (e.g. deck); to sweep"},
    {"kanji": "海","kana": "うみ","eng": "sea; ocean; waters"},
    {"kanji": "消える","kana": "きえる","eng": "to go out; to vanish; to disappear"},
    {"kanji": "消す","kana": "けす","eng": "to erase; to delete; to cross out, to turn off power, to extinguish; to put out, to bump off"},
    {"kanji": "肉","kana": "にく","eng": "flesh, meat, the physical body (as opposed to the spirit), thickness, ink pad"},
    {"kanji": "火曜日","kana": "かようび","eng": "Tuesday"},
    {"kanji": "父","kana": "ちち","eng": "father"},
    {"kanji": "犬","kana": "いぬ","eng": "dog (Canis (lupus) familiaris), snoop (i.e. a detective, a spy, etc.), loser; asshole, counterfeit; inferior; useless; wasteful"},
    {"kanji": "猫","kana": "ねこ","eng": "cat, shamisen, geisha, wheelbarrow, clay bed-warmer, bottom; submissive partner of a homosexual relationship, cat"},
    {"kanji": "生きる","kana": "いきる","eng": "to live; to exist, to make a living; to subsist, to be in effect; to be in use; to function, to come to life; to be enlivened, to be safe (in baseball, go, etc.)"},
    {"kanji": "生徒","kana": "せいと","eng": "pupil"},
    {"kanji": "目","kana": "め, もく","eng": "eye; eyeball, eyesight; sight; vision, look; stare; glance, an experience, viewpoint, stitch; texture; weave, ordinal number suffix, somewhat; -ish, order, item (of a budget revision, etc.), counter for go pieces"},
    {"kanji": "耳","kana": "みみ","eng": "ear, hearing, edge; crust, selvedge (non-fray machined edge of fabrics); selvage"},
    {"kanji": "私","kana": "わたし, わたくし","eng": "I; me"},
    {"kanji": "答える","kana": "こたえる","eng": "to answer; to reply"},
    {"kanji": "窓","kana": "まど","eng": "window"},
    {"kanji": "魚","kana": "さかな","eng": "fish"},
    {"kanji": "今週","kana": "こんしゅう","eng": "this week"},
    {"kanji": "足","kana": "あし","eng": "foot, leg"},
    {"kanji": "花","kana": "はな","eng": "flower"},
    {"kanji": "立つ","kana": "たつ","eng": "to stand"},
    {"kanji": "空","kana": "そら","eng": "sky"},
    {"kanji": "会社","kana": "かいしゃ","eng": "company, corporation"},
    {"kanji": "新しい","kana": "あたらしい","eng": "new"},
    {"kanji": "多い","kana": "おおい","eng": "many"},
    {"kanji": "古い","kana": "ふるい","eng": "old (not person), aged, ancient"},
    {"kanji": "一分","kana": "いっぷん","eng": "one minute"},
    {"kanji": "二分","kana": "にふん","eng": "two minutes"},
    {"kanji": "三分","kana": "さんぷん","eng": "three minutes"},
    {"kanji": "四分","kana": "よんぷん","eng": "four minutes"},
    {"kanji": "五分","kana": "ごふん","eng": "five minutes"},
    {"kanji": "六分","kana": "ろっぷん","eng": "six minutes"},
    {"kanji": "七分","kana": "ななふん","eng": "seven minutes"},
    {"kanji": "八分","kana": "はっぷん","eng": "eight minutes"},
    {"kanji": "九分","kana": "きゅうふん","eng": "nine minutes"},
    {"kanji": "会う","kana": "あう","eng": "to meet, to see"}
];