export const plants = [
    {"kanji": "赤松","kana": "あかまつ","eng": "Japanese red pine (Pinus densiflora), Japanese umbrella pine, tanyosho pine"},
    {"kanji": "朝顔","kana": "あさがお","eng": "Japanese morning glory (Ipomoea nil, Pharbitis nil)"},
    {"kanji": "紫陽花","kana": "あじさい","eng": "bigleaf hydrangea (Hydrangea macrophylla), French hydrangea"},
    {"kanji": "菖蒲","kana": "しょうぶ, そうぶ, あやめ","eng": "sweet flag (Acorus calamus), calamus, iris (flower)"},
    {"kanji": "文目","kana": "あやめ","eng": "pattern, design, distinction"},
    {"kanji": "銀杏","kana": "いちょう, ぎんなん","eng": "ginkgo (Ginkgo biloba), gingko, maidenhair tree, ginkgo nut, gingko nut"},
    {"kanji": "公孫樹","kana": "いちょう, こうそんじゅ","eng": "ginkgo (Ginkgo biloba), gingko, maidenhair tree"},
    {"kanji": "鴨脚樹","kana": "いちょう","eng": "ginkgo (Ginkgo biloba), gingko, maidenhair tree"},
    {"kanji": "大葉子","kana": "おおばこ, おんばこ, おばこ","eng": "plantain (esp. Asian plantain, Plantago asiatica)"},
    {"kanji": "弟切草","kana": "おとぎりそう","eng": "Hypericum erectum (species of St. John's wort)"},
    {"kanji": "鬼胡桃","kana": "おにぐるみ","eng": "Manchurian walnut (Juglans mandshurica)"},
    {"kanji": "橄欖","kana": "かんらん","eng": "Chinese white olive (Canarium album)"},
    {"kanji": "槭樹","kana": "かえで","eng": "maple (tree) (Acer spp.)"},
    {"kanji": "楓","kana": "かえで, かえるで, ふう","eng": "maple (tree) (Acer spp.), Formosan sweetgum (Liquidambar formosana)"},
    {"kanji": "燕子花","kana": "かきつばた","eng": "rabbitear iris (Iris laevigata)"},
    {"kanji": "杜若","kana": "かきつばた","eng": "rabbitear iris (Iris laevigata)"},
    {"kanji": "桂","kana": "かつら, けい","eng": "katsura (Cercidiphyllum japonicum), Japanese Judas tree, knight"},
    {"kanji": "桔梗","kana": "ききょう","eng": "Chinese bellflower, Platycodon grandiflorum"},
    {"kanji": "菊","kana": "きく","eng": "chrysanthemum (Chrysanthemum morifolium)"},
    {"kanji": "金木犀","kana": "きんもくせい","eng": "fragrant olive (Osmanthus fragrans var. aurantiacus)"},
    {"kanji": "樟","kana": "くすのき, くす","eng": "camphor tree (Cinnamomum camphora), camphorwood, camphor laurel"},
    {"kanji": "楠","kana": "くすのき, くす","eng": "camphor tree (Cinnamomum camphora), camphorwood, camphor laurel"},
    {"kanji": "梔子","kana": "くちなし, しし","eng": "Cape jasmine (Gardenia jasminoides), Cape jessamine, gardenia"},
    {"kanji": "橡","kana": "どんぐり, とちのき, とち, つるばみ, くぬぎ, くのぎ","eng": "acorn, Japanese horse chestnut (Aesculus turbinata), sawtooth oak (Quercus acutissima)"},
    {"kanji": "椚","kana": "くぬぎ, くのぎ","eng": "sawtooth oak (Quercus acutissima)"},
    {"kanji": "櫟","kana": "くぬぎ, くのぎ, いちい","eng": "sawtooth oak (Quercus acutissima), Quercus gilva (species of oak)"},
    {"kanji": "黒松","kana": "くろまつ","eng": "black pine (Pinus thunbergii), Japanese black pine"},
    {"kanji": "黒百合","kana": "くろゆり","eng": "black lily (Fritillaria camtschatcensis), Kamchatka lily, Kamchatka fritillary"},
    {"kanji": "桑","kana": "くわ","eng": "mulberry (tree)"},
    {"kanji": "月桂樹","kana": "げっけいじゅ","eng": "bay laurel (Laurus nobilis), bay tree, sweet bay, laurel tree"},
    {"kanji": "欅","kana": "けやき","eng": "Japanese zelkova (species of elm-like tree, Zelkowa serrata)"},
    {"kanji": "秋桜","kana": "あきざくら","eng": "cosmos (flower)"},
    {"kanji": "榊","kana": "さかき","eng": "sakaki (species of evergreen sacred to Shinto, Cleyera japonica)"},
    {"kanji": "桜","kana": "さくら","eng": "cherry tree, cherry blossom"},
    {"kanji": "山茶花","kana": "さざんか, さんざか, さんさか, さんちゃか","eng": "sasanqua (Camellia sasanqua)"},
    {"kanji": "百日紅","kana": "さるすべり, ひゃくじつこう","eng": "crape myrtle (Lagerstroemia indica)"},
    {"kanji": "石楠花","kana": "しゃくなげ","eng": "rhododendron"},
    {"kanji": "石南花","kana": "しゃくなげ","eng": "rhododendron"},
    {"kanji": "水仙","kana": "すいせん","eng": "daffodil (esp. Narcissus tazetta var. chinensis), narcissus"},
    {"kanji": "杉","kana": "すぎ","eng": "Japanese cedar (Cryptomeria japonica)"},
    {"kanji": "鈴蘭","kana": "すずらん","eng": "lily of the valley (Convallaria keiskei)"},
    {"kanji": "菫","kana": "すみれ","eng": "violet (any flower of genus Viola, esp. the Fuji dawn, Viola mandshurica)"},
    {"kanji": "染井吉野","kana": "そめいよしの","eng": "Yoshino cherry (Prunus yedoensis)"},
    {"kanji": "蒲公英","kana": "たんぽぽ, ほこうえい","eng": "dandelion (esp. species Taraxacum platycarpum)"},
    {"kanji": "躑躅","kana": "つつじ","eng": "azalea (Rhododendron spp.)"},
    {"kanji": "椿","kana": "つばき","eng": "common camellia, Camellia japonica"},
    {"kanji": "薺","kana": "なずな","eng": "shepherd's purse (Capsella bursa-pastoris)"},
    {"kanji": "棗","kana": "なつめ","eng": "jujube (Ziziphus jujube), Chinese date, red date"},
    {"kanji": "撫子","kana": "なでしこ","eng": "pink (any flower of genus Dianthus, esp. the fringed pink, Dianthus superbus)"},
    {"kanji": "瞿麦","kana": "なでしこ","eng": "pink (any flower of genus Dianthus, esp. the fringed pink, Dianthus superbus)"},
    {"kanji": "庭漆","kana": "にわうるし","eng": "tree of heaven (Ailanthus altissima)"},
    {"kanji": "野薔薇","kana": "のいばら, のばら","eng": "multiflora rose (Rosa multiflora), wild rose"},
    {"kanji": "繁縷","kana": "はこべ, はこべら","eng": "chickweed, stitchwort (Stellaria sp.)"},
    {"kanji": "蓮","kana": "はす, はちす","eng": "sacred lotus (Nelumbo nucifera), Indian lotus, lotus"},
    {"kanji": "花水木","kana": "はなみずき","eng": "flowering dogwood (Cornus florida)"},
    {"kanji": "薔薇","kana": "ばら, しょうび, そうび","eng": "rose"},
    {"kanji": "柊","kana": "ひいらぎ, ひらぎ","eng": "holly olive (Osmanthus heterophyllus), false holly"},
    {"kanji": "疼木","kana": "ひいらぎ","eng": "holly olive (Osmanthus heterophyllus), false holly"},
    {"kanji": "彼岸花","kana": "ひがんばな","eng": "red spider lily (Lycoris radiata), cluster amaryllis"},
    {"kanji": "雛芥子","kana": "ひなげし","eng": "red poppy (Papaver rhoeas), common poppy, coquelicot"},
    {"kanji": "檜","kana": "ひのき, ひ","eng": "hinoki cypress (Chamaecyparis obtusa), Japanese cypress"},
    {"kanji": "桧","kana": "ひのき, ひ","eng": "hinoki cypress (Chamaecyparis obtusa), Japanese cypress"},
    {"kanji": "向日葵","kana": "ひまわり","eng": "sunflower (Helianthus annuus)"},
    {"kanji": "風信子","kana": "ふうしんし","eng": "hyacinth (Hyacinthus orientalis)"},
    {"kanji": "昼顔","kana": "ひるがお","eng": "Japanese bindweed (Calystegia japonica)"},
    {"kanji": "藤","kana": "ふじ","eng": "wisteria (esp. Japanese wisteria, Wisteria floribunda), wistaria"},
    {"kanji": "山毛欅","kana": "ぶな","eng": "Japanese beech (Fagus crenata), Siebold's beech"},
    {"kanji": "椈","kana": "ぶな","eng": "Japanese beech (Fagus crenata), Siebold's beech"},
    {"kanji": "紅花","kana": "べにばな, こうか","eng": "safflower, dyer's safflower, Carthamus tinctorius"},
    {"kanji": "鳳仙花","kana": "ほうせんか","eng": "(garden) balsam, Impatiens balsamina"},
    {"kanji": "鬼灯","kana": "ほおずき, ほおづき, ほうずき","eng": "ground cherry (Physalis alkekengi var. franchetii), husk tomato, Chinese lantern plant"},
    {"kanji": "酸漿","kana": "ほおずき, ほおづき, ほうずき, ぬかずき, かがち","eng": "ground cherry (Physalis alkekengi var. franchetii), husk tomato, Chinese lantern plant"},
    {"kanji": "牡丹","kana": "ぼたん","eng": "tree peony (Paeonia suffruticosa), moutan"},
    {"kanji": "木槿","kana": "むくげ, もくげ","eng": "rose of Sharon (Hibiscus syriacus)"},
    {"kanji": "樅","kana": "もみ","eng": "Japanese fir (Abies firma), momi fir"},
    {"kanji": "山吹","kana": "やまぶき","eng": "kerria (Kerria japonica), Japanese yellow rose"},
    {"kanji": "夕顔","kana": "ゆうがお","eng": "bottle gourd (Lagenaria siceraria, esp. Lagenaria siceraria var. hispida)"},
    {"kanji": "百合","kana": "ゆり, ゆる","eng": "lily (Lilium spp.)"},
    {"kanji": "夜顔","kana": "よるがお","eng": "moonflower (Ipomoea alba)"},
    {"kanji": "蘭","kana": "らん, あららぎ, らに","eng": "orchid, Japanese yew (Taxus cuspidata), thoroughwort (species of boneset, Eupatorium fortunei)"},
    {"kanji": "竜胆","kana": "りんどう, りゅうたん","eng": "gentian (Gentiana scabra var. buergeri), autumn bellflower"},
    {"kanji": "蓮華草","kana": "れんげそう","eng": "Chinese milk vetch (Astragalus sinicus)"}
];