export const prefectures = [
    {"kanji": "北海道","kana": "ほっかいどう","eng": "Hokkaido"},
    {"kanji": "青森県","kana": "あおもりけん","eng": "Aomori Prefecture"},
    {"kanji": "秋田県","kana": "あきたけん","eng": "Akita Prefecture"},
    {"kanji": "岩手県","kana": "いわてけん","eng": "Iwate Prefecture"},
    {"kanji": "山形県","kana": "やまがたけん","eng": "Yamagata Prefecture"},
    {"kanji": "宮城県","kana": "みやぎけん","eng": "Miyagi Prefecture"},
    {"kanji": "福島県","kana": "ふくしまけん","eng": "Fukushima Prefecture"},
    {"kanji": "新潟県","kana": "にいがたけん","eng": "Niigata Prefecture"},
    {"kanji": "富山県","kana": "とやまけん","eng": "Toyama Prefecture"},
    {"kanji": "石川県","kana": "いしかわけん","eng": "Ishikawa Prefecture"},
    {"kanji": "福井県","kana": "ふくいけん","eng": "Fukui Prefecture"},
    {"kanji": "長野県","kana": "ながのけん","eng": "Nagano Prefecture"},
    {"kanji": "群馬県","kana": "ぐんまけん","eng": "Gunma Prefecture"},
    {"kanji": "栃木県","kana": "とちぎけん","eng": "Tochigi Prefecture"},
    {"kanji": "茨城県","kana": "いばらきけん","eng": "Ibaraki Prefecture"},
    {"kanji": "千葉県","kana": "ちばけん","eng": "Chiba Prefecture"},
    {"kanji": "埼玉県","kana": "さいたまけん","eng": "Saitama Prefecture"},
    {"kanji": "東京都","kana": "とうきょうと","eng": "Tokyo"},
    {"kanji": "神奈川県","kana": "かながわけん","eng": "Kanagawa Prefecture"},
    {"kanji": "山梨県","kana": "やまなしけん","eng": "Yamanashi Prefecture"},
    {"kanji": "静岡県","kana": "しずおかけん","eng": "Shizuoka Prefecture"},
    {"kanji": "愛知県","kana": "あいちけん","eng": "Aichi Prefecture"},
    {"kanji": "岐阜県","kana": "ぎふけん","eng": "Gifu Prefecture"},
    {"kanji": "三重県","kana": "みえけん","eng": "Mie Prefecture"},
    {"kanji": "滋賀県","kana": "しがけん","eng": "Shiga Prefecture"},
    {"kanji": "京都府","kana": "きょうとふ","eng": "Kyoto"},
    {"kanji": "大阪府","kana": "おおさかふ","eng": "Osaka"},
    {"kanji": "奈良県","kana": "ならけん","eng": "Nara Prefecture"},
    {"kanji": "和歌山県","kana": "わかやまけん","eng": "Wakayama Prefecture"},
    {"kanji": "兵庫県","kana": "ひょうごけん","eng": "Hyogo Prefecture"},
    {"kanji": "鳥取県","kana": "とっとりけん","eng": "Tottori"},
    {"kanji": "島根県","kana": "しまねけん","eng": "Shimane Prefecture"},
    {"kanji": "岡山県","kana": "おかやまけん","eng": "Okayama Prefecture"},
    {"kanji": "広島県","kana": "ひろしまけん","eng": "Hiroshima Prefecture"},
    {"kanji": "山口県","kana": "やまぐちけん","eng": "Yamaguchi Prefecture"},
    {"kanji": "香川県","kana": "かがわけん","eng": "Kagawa Prefecture"},
    {"kanji": "徳島県","kana": "とくしまけん","eng": "Tokushima Prefecture"},
    {"kanji": "高知県","kana": "こうちけん","eng": "Kochi Prefecture"},
    {"kanji": "愛媛県","kana": "えひめけん","eng": "Ehime Prefecture"},
    {"kanji": "福岡県","kana": "ふくおかけん","eng": "Fukuoka Prefecture"},
    {"kanji": "大分県","kana": "おおいたけん","eng": "Oita Prefecture"},
    {"kanji": "宮崎県","kana": "みやざきけん","eng": "Miyazaki Prefecture"},
    {"kanji": "熊本県","kana": "くまもとけん","eng": "Kumamoro Prefecture"},
    {"kanji": "鹿児島県","kana": "かごしまけん","eng": "Kagoshima Prefecture"},
    {"kanji": "佐賀県","kana": "さがけん","eng": "Saga Prefecture"},
    {"kanji": "長崎県","kana": "ながさきけん","eng": "Nagasaki Prefecture"},
    {"kanji": "沖縄県","kana": "おきなわけん","eng": "Okinawa Prefecture"}
];