export const vegetables = [
    {"kanji": "通草","kana": "あけび","eng": "chocolate-vine (Akebia quinata), fiveleaf, fiveleaf akebia"},
    {"kanji": "木通","kana": "あけび","eng": "chocolate-vine (Akebia quinata), fiveleaf, fiveleaf akebia"},
    {"kanji": "鰐梨","kana": "わになし","eng": "avocado (Persea americana), alligator pear"},
    {"kanji": "杏","kana": "あんず","eng": "apricot (Prunus armeniaca)"},
    {"kanji": "杏子","kana": "あんず","eng": "apricot (Prunus armeniaca)"},
    {"kanji": "苺","kana": "いちご","eng": "strawberry (esp. the garden strawberry, Fragaria x ananassa)"},
    {"kanji": "無花果","kana": "いちじく, いちぢく, いちじゅく, むかか","eng": "common fig (Ficus carica), fig, fig tree"},
    {"kanji": "梅","kana": "うめ, むめ","eng": "Japanese apricot (Prunus mume), Chinese plum"},
    {"kanji": "柿","kana": "かき, こけら","eng": "kaki, Japanese persimmon (Diospyros kaki), chopped wood, wood chips"},
    {"kanji": "巨峰","kana": "きょほう","eng": "gigantic peak"},
    {"kanji": "金柑","kana": "きんかん","eng": "kumquat (Fortunella spp.), cumquat"},
    {"kanji": "栗","kana": "くり","eng": "Japanese chestnut (Castanea crenata)"},
    {"kanji": "桜桃","kana": "さくらんぼ, さくらんぼう, おうとう, ゆすらうめ, ゆすら","eng": "cherry fruit (esp. sweet cherry, Prunus avium), cherry (tree; esp. sweet cherry or Nanking cherry), Nanking cherry (Prunus tomentosa), downy cherry"},
    {"kanji": "石榴","kana": "ざくろ, せきりゅう, じゃくろ","eng": "pomegranate (Punica granatum)"},
    {"kanji": "李","kana": "すもも","eng": "Japanese plum (Prunus salicina), Chinese plum"},
    {"kanji": "梨","kana": "なし","eng": "nashi (Pyrus pyrifolia, esp. var. culta), Japanese pear, Asian pear, sand pear, apple pear"},
    {"kanji": "鳳梨","kana": "ほうり","eng": "pineapple"},
    {"kanji": "八朔","kana": "はっさく","eng": "Hassaku orange (Citrus hassaku)"},
    {"kanji": "甘蕉","kana": "かんしょう","eng": "banana"},
    {"kanji": "実芭蕉","kana": "みばしょう","eng": "banana"},
    {"kanji": "木瓜","kana": "ぼけ, ぼっか, もけ, もっこう, もこう","eng": "Japanese quince (Chaenomeles speciosa), flowering quince, family crest based on a japonica flower"},
    {"kanji": "枇杷","kana": "びわ","eng": "loquat (Eriobotrya japonica), Japanese medlar"},
    {"kanji": "葡萄","kana": "ぶどう, えび","eng": "grape, grapevine"},
    {"kanji": "蜜柑","kana": "みかん","eng": "mandarin orange (esp. the satsuma mandarin, Citrus unshiu)"},
    {"kanji": "桃","kana": "もも","eng": "peach (Prunus persica)"},
    {"kanji": "柚子","kana": "ゆず","eng": "yuzu (Citrus ichangensis x C. reticulata)"},
    {"kanji": "茘枝","kana": "れいし","eng": "litchi (Nephelium litchi), lychee, lichee, litchi nut"},
    {"kanji": "林檎","kana": "りんご, りゅうごう, りんきん, りんき","eng": "apple (fruit)"},
    {"kanji": "檸檬","kana": "れもん","eng": "lemon"},
    {"kanji": "小豆","kana": "あずき, しょうず","eng": "adzuki bean (Vigna angularis)"},
    {"kanji": "隠元豆","kana": "いんげんまめ","eng": "common bean (Phaseolus vulgaris), kidney bean, navy bean, wax bean, green bean, string bean, French bean"},
    {"kanji": "榎茸","kana": "えのきたけ, えのきだけ","eng": "enoki mushroom (Flammulina velutipes), winter mushroom, velvet shank, enokitake, enokidake"},
    {"kanji": "蕪","kana": "かぶ, かぶら, かぶな","eng": "turnip (Brassica rapa)"},
    {"kanji": "南瓜","kana": "かぼちゃ, ぼうぶら, なんか","eng": "pumpkin (Cucurbita sp.), squash"},
    {"kanji": "花椰菜","kana": "はなやさい","eng": "cauliflower"},
    {"kanji": "木耳","kana": "きくらげ","eng": "cloud ear mushroom (Auricularia auricula-judae), wood ear mushroom, Jew's ear mushroom"},
    {"kanji": "甘藍","kana": "かんらん","eng": "cabbage"},
    {"kanji": "胡瓜","kana": "きゅうり","eng": "cucumber (Cucumis sativus)"},
    {"kanji": "青豌豆","kana": "あおえんどう","eng": "green peas"},
    {"kanji": "慈姑","kana": "くわい","eng": "Sagittaria trifolia var. edulis (edible variant of threeleaf arrowhead)"},
    {"kanji": "苦瓜","kana": "にがうり","eng": "bitter melon (Momordica charantia), bitter gourd"},
    {"kanji": "胡椒","kana": "こしょう","eng": "pepper"},
    {"kanji": "牛蒡","kana": "ごぼう, ごんぼ, うまふぶき","eng": "great burdock (Arctium lappa)"},
    {"kanji": "胡麻","kana": "ごま","eng": "sesame seeds"},
    {"kanji": "薩摩芋","kana": "さつまいも","eng": "sweet potato (Ipomoea batatas)"},
    {"kanji": "甘藷","kana": "さつまいも, かんしょ","eng": "sweet potato (Ipomoea batatas), sweet potato"},
    {"kanji": "里芋","kana": "さといも","eng": "taro (Colocasia esculenta), dasheen, eddo"},
    {"kanji": "莢隠元","kana": "さやいんげん","eng": "French beans, string beans"},
    {"kanji": "莢豌豆","kana": "さやえんどう","eng": "peas, garden peas, field peas"},
    {"kanji": "山椒","kana": "さんしょう, さんしょ","eng": "Japanese pepper (species of Sichuan pepper, Zanthoxylum piperitum), Japanese prickly ash"},
    {"kanji": "椎茸","kana": "しいたけ","eng": "shiitake mushroom (Lentinula edodes)"},
    {"kanji": "香蕈","kana": "しいたけ","eng": "shiitake mushroom (Lentinula edodes)"},
    {"kanji": "紫蘇","kana": "しそ, ちそ","eng": "shiso (Perilla frutescens var. crispa), perilla, beefsteak plant"},
    {"kanji": "自然薯","kana": "じねんじょ","eng": "Japanese yam (Dioscorea japonica)"},
    {"kanji": "湿地","kana": "しっち, しめじ","eng": "wetland, wetlands, Lyophyllum shimeji (species of edible mushroom)"},
    {"kanji": "生姜","kana": "しょうが, しょうきょう","eng": "ginger (Zingiber officinale), dried ginger root (trad. medicine)"},
    {"kanji": "西瓜","kana": "すいか","eng": "watermelon (Citrullus lanatus)"},
    {"kanji": "薇","kana": "ぜんまい","eng": "royal fern (Osmunda japonica), flowering fern, osmund, fiddlehead fern"},
    {"kanji": "空豆","kana": "そらまめ","eng": "broad bean (Vicia faba), horse bean, fava bean"},
    {"kanji": "蚕豆","kana": "そらまめ","eng": "broad bean (Vicia faba), horse bean, fava bean"},
    {"kanji": "大根","kana": "だいこん, だいこ, おおね","eng": "daikon (variety of large white Oriental radish, Raphanus sativus var. longipinnatus), root, source, origin, basis"},
    {"kanji": "大豆","kana": "だいず","eng": "soya bean (Glycine max), soybean, soy"},
    {"kanji": "筍","kana": "たけのこ, たかんな, たかむな, たこうな","eng": "bamboo shoot"},
    {"kanji": "笋","kana": "たけのこ, たかんな, たかむな, たこうな","eng": "bamboo shoot"},
    {"kanji": "玉葱","kana": "たまねぎ","eng": "onion (Allium cepa)"},
    {"kanji": "青梗菜","kana": "チンゲンサイ, ちんげんさい, チンゲンさい","eng": "bok-choy (Brassica rapa var. chinensis), Chinese cabbage, bok choi, pak choi"},
    {"kanji": "唐辛子","kana": "とうがらし, とんがらし","eng": "capsicum (Capsicum annuum, esp. the cultivated chili peppers), chili pepper (chile, chilli), cayenne, red pepper, Chili pepper"},
    {"kanji": "蕃椒","kana": "とうがらし, ばんしょう","eng": "capsicum (Capsicum annuum, esp. the cultivated chili peppers), chili pepper (chile, chilli), cayenne, red pepper"},
    {"kanji": "冬瓜","kana": "とうがん, とうが","eng": "wax gourd (Benincasa hispida), ash gourd, white gourd, winter melon"},
    {"kanji": "玉蜀黍","kana": "とうもろこし","eng": "corn (Zea mays), maize"},
    {"kanji": "蕃茄","kana": "ばんか","eng": "tomato (Solanum lycopersicum)"},
    {"kanji": "赤茄子","kana": "あかなす","eng": "Chinese scarlet eggplant (Solanum integrifolium), tomato-fruit eggplant"},
    {"kanji": "茄子","kana": "なす, なすび","eng": "eggplant (Solanum melongena), aubergine"},
    {"kanji": "韮","kana": "にら, みら, かみら","eng": "Chinese chive, garlic chive (Allium tuberosum)"},
    {"kanji": "人参","kana": "にんじん","eng": "carrot (Daucus carota)"},
    {"kanji": "胡蘿蔔","kana": "こらふ","eng": "carrot"},
    {"kanji": "大蒜","kana": "にんにく","eng": "garlic (Allium sativum)"},
    {"kanji": "葫","kana": "にんにく, ひる","eng": "garlic (Allium sativum), strong-smelling edible plant (esp. perennials of the family Liliaceae, e.g. Welsh onion, garlic, wild rocambole, etc.)"},
    {"kanji": "葱","kana": "ねぎ, き","eng": "Welsh onion (species of scallion, Allium fistulosum), green onion, spring onion"},
    {"kanji": "白菜","kana": "はくさい","eng": "Chinese cabbage (Brassica campestris var. amplexicaulis), white rape, bok choy, pak choi"},
    {"kanji": "和蘭芹","kana": "オランダぜり, おらんだぜり","eng": "parsley (Petroselinum crispum)"},
    {"kanji": "馬鈴薯","kana": "ばれいしょ","eng": "potato (Solanum tuberosum)"},
    {"kanji": "葫蘆","kana": "ころ","eng": "calabash (Lagenaria siceraria)"},
    {"kanji": "瓢箪","kana": "ひょうたん","eng": "gourd, calabash (Lagenaria siceraria var. gourda)"},
    {"kanji": "蕗","kana": "ふき, ふふき","eng": "giant butterbur (Petasites japonicus), Japanese sweet coltsfoot"},
    {"kanji": "糸瓜","kana": "へちま","eng": "sponge gourd (Luffa aegyptiaca), Egyptian cucumber, Vietnamese luffa, dishrag gourd"},
    {"kanji": "天糸瓜","kana": "へちま","eng": "sponge gourd (Luffa aegyptiaca), Egyptian cucumber, Vietnamese luffa, dishrag gourd"},
    {"kanji": "菠薐草","kana": "ほうれんそう","eng": "spinach"},
    {"kanji": "法蓮草","kana": "ほうれんそう","eng": "spinach"},
    {"kanji": "鳳蓮草","kana": "ほうれんそう","eng": "spinach"},
    {"kanji": "豆","kana": "まめ","eng": "legume (esp. edible legumes or their seeds, such as beans, peas, pulses, etc.), beans, peas"},
    {"kanji": "茗荷","kana": "みょうが","eng": "Japanese ginger (Zingiber mioga)"},
    {"kanji": "辣韮","kana": "らっきょう, らっきょ","eng": "Japanese leek (Allium chinense), Chinese onion"},
    {"kanji": "薤","kana": "らっきょう, らっきょ","eng": "Japanese leek (Allium chinense), Chinese onion"},
    {"kanji": "萵苣","kana": "ちしゃ, ちさ","eng": "lettuce"},
    {"kanji": "蓮根","kana": "れんこん, はすね","eng": "lotus root"},
    {"kanji": "山葵","kana": "わさび","eng": "wasabi (Wasabia japonica)"}
];